"""橋梁モデル (./brid/)"""

from .base import (
    FeatureEmission,
    FeatureEmissions,
    FeatureProcessingDefinition,
    LODDetection,
    Property,
    PropertyGroup,
)
from .common import facility_id_attribute_attrs

BRIDGE = FeatureProcessingDefinition(
    id="Bridge",
    target_elements=["brid:Bridge"],
    lod_detection=LODDetection(
        lod1=["./brid:lod1Solid"],
        lod2=["./brid:lod2Solid", "./brid:lod2MultiSurface"],
        lod3=["./brid:lod3Solid", "./brid:lod3MultiSurface"],
        lod4=["./brid:lod4Solid", "./brid:lod4MultiSurface"],
    ),
    property_groups=[
        PropertyGroup(
            base_element=None,
            properties=[
                Property(
                    name="class",
                    path="./brid:class",
                    datatype="string",
                    predefined_codelist="Bridge_class",
                ),
                Property(
                    name="function",
                    path="./brid:function",
                    datatype="[]string",
                    predefined_codelist="Bridge_function",
                ),
                Property(
                    name="yearOfConstruction",
                    path="./brid:yearOfConstruction",
                    datatype="integer",
                ),
                Property(
                    name="yearOfDemolition",
                    path="./brid:yearOfDemolition",
                    datatype="integer",
                ),
                Property(
                    name="isMovable",
                    path="./brid:isMovable",
                    datatype="boolean",
                ),
            ],
        ),
        PropertyGroup(
            base_element="./uro:bridBaseAttribute/uro:ConstructionBaseAttribute",
            properties=[
                Property(
                    name="adminOffice",
                    path="./uro:adminOffice",
                    datatype="string",
                ),
                Property(
                    name="adminType",
                    path="./uro:adminType",
                    datatype="string",
                    predefined_codelist="ConstructionBaseAttribute_adminType",
                ),
                Property(
                    name="administorator",
                    path="./uro:administorator",
                    datatype="string",
                ),
                Property(
                    name="completionYear",
                    path="./uro:completionYear",
                    datatype="integer",
                ),
                Property(
                    name="constructionStartYear",
                    path="./uro:constructionStartYear",
                    datatype="integer",
                ),
                Property(
                    name="facilityAge",
                    path="./uro:facilityAge",
                    datatype="integer",
                ),
                Property(
                    name="installer",
                    path="./uro:installer",
                    datatype="string",
                ),
                Property(
                    name="installerType",
                    path="./uro:installerType",
                    datatype="string",
                    predefined_codelist="ConstructionBaseAttribute_installerType",
                ),
                Property(
                    name="kana",
                    path="./uro:kana",
                    datatype="string",
                ),
                Property(
                    name="operatorType",
                    path="./uro:operatorType",
                    datatype="string",
                    predefined_codelist=None,
                ),
                Property(
                    name="purpose",
                    path="./uro:purpose",
                    datatype="string",
                    predefined_codelist="ConstructionBaseAttribute_purpose",
                ),
                Property(
                    name="specification",
                    path="./uro:specification",
                    datatype="string",
                ),
                Property(
                    name="structureOrdinance",
                    path="./uro:structureOrdinance",
                    datatype="string",
                ),
                Property(
                    name="update",
                    path="./uro:update",
                    datatype="date",
                ),
            ],
        ),
        PropertyGroup(
            base_element="./uro:bridStructureAttribute/uro:BridgeStructureAttribute",
            properties=[
                Property(
                    name="bridgeType",
                    path="./uro:bridgeType",
                    datatype="string",
                    predefined_codelist="BridgeStructureAttribute_bridgeType",
                ),
                Property(
                    name="escalator",
                    path="./uro:escalator",
                    datatype="boolean",
                ),
                Property(
                    name="material",
                    path="./uro:material",
                    datatype="string",
                    predefined_codelist="BridgeStructureAttribute_material",
                ),
                Property(
                    name="slopeType",
                    path="./uro:slopeType",
                    datatype="string",
                    predefined_codelist="ConstructionStructureAttribute_slopeType",
                ),
            ],
        ),
        PropertyGroup(
            base_element="./uro:bridFunctionalAttribute/uro:BridgeFunctionalAttribute",
            properties=[
                Property(
                    name="directionType",
                    path="./uro:directionType",
                    datatype="string",
                    predefined_codelist=None,
                ),
                Property(
                    name="userType",
                    path="./uro:userType",
                    datatype="string",
                    predefined_codelist=None,
                ),
            ],
        ),
        PropertyGroup(
            base_element="./uro:bridRiskAssessmentAttribute/uro:ConstructionRiskAssessmentAttribute",
            properties=[
                Property(
                    name="referenceDate",
                    path="./uro:referenceDate",
                    datatype="date",
                ),
                Property(
                    name="riskType",
                    path="./uro:riskType",
                    datatype="string",
                    predefined_codelist="ConstructionRiskAssessmentAttribute_riskType",
                ),
                Property(
                    name="status",
                    path="./uro:status",
                    datatype="string",
                    predefined_codelist="ConstructionRiskAssessmentAttribute_status",
                ),
                Property(
                    name="surveyYear",
                    path="./uro:surveyYear",
                    datatype="integer",
                ),
            ],
        ),
        PropertyGroup(
            base_element="./uro:bridDataQualityAttribute/uro:ConstructionDataQualityAttribute",
            properties=[
                Property(
                    name="appearanceSrcDesc",
                    path="./uro:appearanceSrcDesc",
                    datatype="[]string",
                    predefined_codelist="DataQualityAttribute_appearanceSrcDesc",
                ),
                Property(
                    name="dataAcquisition",
                    path="./uro:dataAcquisition",
                    datatype="string",
                ),
                Property(
                    name="geometrySrcDesc",
                    path="./uro:geometrySrcDesc",
                    datatype="[]string",
                    predefined_codelist="DataQualityAttribute_geometrySrcDesc",
                ),
                Property(
                    name="lod1HeightType",
                    path="./uro:lod1HeightType",
                    datatype="string",
                    predefined_codelist="DataQualityAttribute_lod1HeightType",
                ),
                Property(
                    name="lodType",
                    path="./uro:lodType",
                    datatype="[]string",
                ),
                Property(
                    name="photoScale",
                    path="./uro:photoScale",
                    datatype="integer",
                ),
                Property(
                    name="srcScale",
                    path="./uro:srcScale",
                    datatype="string",
                    predefined_codelist="DataQualityAttribute_srcScale",
                ),
                Property(
                    name="thematicSrcDesc",
                    path="./uro:thematicSrcDesc",
                    datatype="[]string",
                    predefined_codelist="DataQualityAttribute_thematicSrcDesc",
                ),
            ],
        ),
        PropertyGroup(
            base_element="./uro:bridFacilityIdAttribute/uro:FacilityIdAttribute",
            properties=facility_id_attribute_attrs,
        ),
        # TODO: uro:bridDisasterRiskAttribute (入れ子、polymorhpic)
        # TODO: uro:bridFacilityTypeAttribute
        # TODO: uro:bridFacilityAttribute
        # TODO: uro:bridDmAttribute
    ],
    emissions=FeatureEmissions(
        lod1=FeatureEmission(collect_all=["./brid:lod1Solid//gml:Polygon"]),
        lod2=FeatureEmission(
            collect_all=[
                ".//brid:lod2MultiSurface//gml:Polygon",
                ".//brid:lod2Geometry//gml:Polygon",
            ],
            only_direct=[
                "./brid:lod2MultiSurface//gml:Polygon",
                "./brid:lod2Geometry//gml:Polygon",
            ],
        ),
        lod3=FeatureEmission(
            collect_all=[
                ".//brid:lod3MultiSurface//gml:Polygon",
                ".//brid:lod3Geometry//gml:Polygon",
            ],
            only_direct=[
                "./brid:lod3MultiSurface//gml:Polygon",
                "./brid:lod3Geometry//gml:Polygon",
            ],
        ),
        semantic_parts=[
            ".//brid:GroundSurface",
            ".//brid:WallSurface",
            ".//brid:RoofSurface",
            ".//brid:OuterCeilingSurface",
            ".//brid:OuterFloorSurface",
            ".//brid:ClosureSurface",
            ".//brid:CeilingSurface",
            ".//brid:InteriorWallSurface",
            ".//brid:FloorSurface",
            ".//brid:BridgeInstallation",
            ".//brid:IntBridgeInstallation",
            ".//brid:BridgeConstructionElement",
            ".//brid:BridgeFurniture",
        ],
    ),
)

BRIDGE_BOUNDARY_SURFACE = FeatureProcessingDefinition(
    id="brid:_BoundarySurface",
    target_elements=[
        "brid:GroundSurface",
        "brid:WallSurface",
        "brid:RoofSurface",
        "brid:OuterCeilingSurface",
        "brid:OuterFloorSurface",
        "brid:ClosureSurface",
        "brid:InteriorWallSurface",
        "brid:CeilingSurface",
        "brid:FloorSurface",
    ],
    property_groups=[],
    lod_detection=LODDetection(
        lod2=["./brid:lod2MultiSurface"],
        lod3=["./brid:lod3MultiSurface"],
        lod4=["./brid:lod4MultiSurface"],
    ),
    emissions=FeatureEmissions(
        lod2=FeatureEmission(
            collect_all=[
                ".//brid:lod2MultiSurface//gml:Polygon",
                ".//brid:lod2Geometry//gml:Polygon",
            ]
        ),
        lod3=FeatureEmission(
            collect_all=[
                ".//brid:lod3MultiSurface//gml:Polygon",
                ".//brid:lod3Geometry//gml:Polygon",
            ]
        ),
        lod4=FeatureEmission(
            collect_all=[
                ".//brid:lod4MultiSurface//gml:Polygon",
                ".//brid:lod4Geometry//gml:Polygon",
            ]
        ),
        semantic_parts=[
            "./brid:opening/brid:Door",
            "./brid:opening/brid:Window",
        ],
    ),
)

BRIDGE_OPENING = FeatureProcessingDefinition(
    id="brid:_Opening",
    target_elements=[
        "brid:Window",
        "brid:Door",
    ],
    property_groups=[],
    lod_detection=LODDetection(
        lod3=["./brid:lod3MultiSurface"],
        lod4=["./brid:lod4MultiSurface"],
    ),
    emissions=FeatureEmissions(
        lod3=FeatureEmission(collect_all=[".//brid:lod3MultiSurface//gml:Polygon"]),
        lod4=FeatureEmission(collect_all=[".//brid:lod4MultiSurface//gml:Polygon"]),
    ),
)

BRIDGE_CONSTRUCTION_ELEMENT = FeatureProcessingDefinition(
    id="BridgeConstructionElement",
    target_elements=[
        "brid:BridgeConstructionElement",
    ],
    property_groups=[
        PropertyGroup(
            base_element=None,
            properties=[
                Property(
                    name="function",
                    path="./brid:function",
                    datatype="[]string",
                    predefined_codelist="BridgeConstructionElement_function",
                ),
            ],
        )
    ],
    lod_detection=LODDetection(
        lod2=["./brid:lod2Geometry"],
        lod3=["./brid:lod3Geometry"],
        lod4=["./brid:lod4Geometry"],
    ),
    emissions=FeatureEmissions(
        lod2=FeatureEmission(collect_all=[".//brid:lod2Geometry//gml:Polygon"]),
        lod3=FeatureEmission(collect_all=[".//brid:lod3Geometry//gml:Polygon"]),
        lod4=FeatureEmission(collect_all=[".//brid:lod4Geometry//gml:Polygon"]),
    ),
)

BRIDGE_INSTALLATION = FeatureProcessingDefinition(
    id="BridgeInstallation",
    target_elements=[
        "brid:BridgeInstallation",
    ],
    property_groups=[
        PropertyGroup(
            base_element=None,
            properties=[
                Property(
                    name="class",
                    path="./brid:class",
                    datatype="string",
                ),
                Property(
                    name="function",
                    path="./brid:function",
                    datatype="[]string",
                    predefined_codelist="BridgeInstallation_function",
                ),
                Property(
                    name="usage",
                    path="./brid:usage",
                    datatype="[]string",
                ),
            ],
        )
    ],
    lod_detection=LODDetection(
        lod2=["./brid:lod2Geometry"],
        lod3=["./brid:lod3Geometry"],
        lod4=["./brid:lod4Geometry"],
    ),
    emissions=FeatureEmissions(
        lod2=FeatureEmission(collect_all=[".//brid:lod2Geometry//gml:Polygon"]),
        lod3=FeatureEmission(collect_all=[".//brid:lod3Geometry//gml:Polygon"]),
        lod4=FeatureEmission(collect_all=[".//brid:lod4Geometry//gml:Polygon"]),
    ),
)


BRIDGE_INT_INSTALLATION = FeatureProcessingDefinition(
    id="IntBridgeInstallation",
    target_elements=[
        "brid:IntBridgeInstallation",
    ],
    property_groups=[
        PropertyGroup(
            base_element=None,
            properties=[
                Property(
                    name="class",
                    path="./brid:class",
                    datatype="string",
                ),
                Property(
                    name="function",
                    path="./brid:function",
                    datatype="[]string",
                    predefined_codelist="IntBridgeInstallation_function",
                ),
            ],
        )
    ],
    lod_detection=LODDetection(
        lod2=["./brid:lod2Geometry"],
        lod3=["./brid:lod3Geometry"],
        lod4=["./brid:lod4Geometry"],
    ),
    emissions=FeatureEmissions(
        lod2=FeatureEmission(collect_all=[".//brid:lod2Geometry//gml:Polygon"]),
        lod3=FeatureEmission(collect_all=[".//brid:lod3Geometry//gml:Polygon"]),
        lod4=FeatureEmission(collect_all=[".//brid:lod4Geometry//gml:Polygon"]),
    ),
)


BRIDGE_FURNITURE = FeatureProcessingDefinition(
    id="BridgeFurniture",
    target_elements=[
        "brid:BridgeFurniture",
    ],
    property_groups=[
        PropertyGroup(
            base_element=None,
            properties=[
                Property(
                    name="function",
                    path="./brid:function",
                    datatype="[]string",
                    predefined_codelist="BridgeFurniture_function",
                ),
            ],
        ),
    ],
    lod_detection=LODDetection(
        lod4=["./brid:lod4Geometry"],
    ),
    emissions=FeatureEmissions(
        lod4=FeatureEmission(collect_all=[".//brid:lod4Geometry//gml:Polygon"]),
    ),
)
