from .base import (
    FeatureEmission,
    FeatureEmissions,
    LODDetection,
    ProcessorDefinition,
    Property,
    PropertyGroup,
)

BUILDING = ProcessorDefinition(
    id="Building",
    target_elements=["bldg:Building"],
    lod_detection=LODDetection(
        lod1=["./bldg:lod1Solid"],
        lod2=["./bldg:lod2Solid"],
        lod3=["./bldg:lod3Solid"],
        # lod4=["./bldg:lod4Solid", "./bldg:lod4MultiSurface"],
    ),
    property_groups=[
        PropertyGroup(
            base_element=None,
            properties=[
                Property(
                    name="usage",
                    path="./bldg:usage",
                    datatype="[]string",
                    codelist="Building_usage",
                ),
                Property(
                    name="yearOfConstruction",
                    path="./bldg:yearOfConstruction",
                    datatype="integer",
                ),
                Property(
                    name="yearOfDemolition",
                    path="./bldg:yearOfDemolition",
                    datatype="integer",
                ),
                Property(
                    name="roofType",
                    path="./bldg:roofType",
                    datatype="string",
                    codelist="Building_roofType",
                ),
                Property(
                    name="measuredHeight",
                    path="./bldg:measuredHeight",
                    datatype="double",
                ),
                # Property(
                #     name="address",
                #     path="./bldg:address",
                #     datatype="string",  # xAL をどう読むか
                # ),
                Property(
                    name="storeysAboveGround",
                    path="./bldg:storeysAboveGround",
                    datatype="integer",
                ),
                Property(
                    name="storeysBelowGround",
                    path="./bldg:storeysBelowGround",
                    datatype="integer",
                ),
            ],
        ),
        # uro
        PropertyGroup(
            base_element="./uro:buildingDetailAttribute/uro:BuildingDetailAttribute",
            properties=[
                Property(
                    name="uro:serialNumberOfBuildingCertification",
                    path="./uro:serialNumberOfBuildingCertification",
                    datatype="string",
                ),
                Property(
                    name="uro:siteArea",
                    path="./uro:siteArea",
                    datatype="double",
                ),
                Property(
                    name="uro:totalFloorArea",
                    path="./uro:totalFloorArea",
                    datatype="double",
                ),
                Property(
                    name="uro:buildingFootprintArea",
                    path="./uro:buildingFootprintArea",
                    datatype="double",
                ),
                Property(
                    name="uro:buildingRoofEdgeArea",
                    path="./uro:buildingRoofEdgeArea",
                    datatype="double",
                ),
                Property(
                    name="uro:developmentArea",
                    path="./uro:developmentArea",
                    datatype="double",
                ),
                Property(
                    name="uro:buildingStructureType",
                    path="./uro:buildingStructureType",
                    datatype="string",
                    codelist="BuildingDetailAttribute_buildingStructureType",
                ),
                Property(
                    name="uro:buildingStructureOrgType",
                    path="./uro:buildingStructureOrgType",
                    datatype="string",
                    # codelist="(custom)",
                ),
                Property(
                    name="uro:fireproofStructureType",
                    path="./uro:fireproofStructureType",
                    datatype="string",
                    codelist="BuildingDetailAttribute_fireproofStructureType",
                ),
                Property(
                    name="uro:urbanPlanType",
                    path="./uro:urbanPlanType",
                    datatype="string",
                    codelist="BuildingDetailAttribute_urbanPlanType",
                ),
                Property(
                    name="uro:areaClassificationType",
                    path="./uro:areaClassificationType",
                    datatype="string",
                    codelist="Common_areaClassificationType",
                ),
                Property(
                    name="uro:districtsAndZonesType",
                    path="./uro:districtsAndZonesType",
                    datatype="string",
                    codelist="Common_districtsAndZonesType",
                ),
                Property(
                    name="uro:majorUsage",
                    path="./uro:majorUsage",
                    datatype="string",
                ),
                Property(
                    name="uro:majorUsage2",
                    path="./uro:majorUsage2",
                    datatype="string",
                ),
                Property(
                    name="uro:buildingCoverageRate",
                    path="./uro:buildingCoverageRate",
                    datatype="double",
                ),
                Property(
                    name="uro:floorAreaRate",
                    path="./uro:floorAreaRate",
                    datatype="double",
                ),
                Property(
                    name="uro:specifiedBuildingCoverageRate",
                    path="./uro:specifiedBuildingCoverageRate",
                    datatype="double",
                ),
                Property(
                    name="uro:specifiedFloorAreaRate",
                    path="./uro:specifiedFloorAreaRate",
                    datatype="double",
                ),
                Property(
                    name="uro:standardFloorAreaRate",
                    path="./uro:standardFloorAreaRate",
                    datatype="double",
                ),
                Property(
                    name="uro:buidingHeight",
                    path="./uro:buidingHeight",
                    datatype="double",
                ),
                Property(
                    name="uro:eaveHeight",
                    path="./uro:eaveHeight",
                    datatype="double",
                ),
                Property(
                    name="uro:surveyYear",
                    path="./uro:surveyYear",
                    datatype="integer",
                ),
            ],
        ),
    ],
    emissions=FeatureEmissions(
        lod1=FeatureEmission(catch_all=[".//bldg:lod1Solid//gml:Polygon"]),
        lod2=FeatureEmission(
            catch_all=[".//bldg:lod2MultiSurface//gml:Polygon"],
            direct=["./bldg:lod2MultiSurface//gml:Polygon"],
        ),
        lod3=FeatureEmission(
            catch_all=[".//bldg:lod3MultiSurface//gml:Polygon"],
            direct=["./bldg:lod3MultiSurface//gml:Polygon"],
        ),
        semantic_parts=[
            ".//bldg:GroundSurface",
            ".//bldg:WallSurface",
            ".//bldg:RoofSurface",
            ".//bldg:OuterCeilingSurface",
            ".//bldg:OuterFloorSurface",
            ".//bldg:ClosureSurface",
        ],
    ),
)

BUILDING_BOUNDARY_SURFACE = ProcessorDefinition(
    id="bldg:_BoundarySurface",
    target_elements=[
        "bldg:GroundSurface",
        "bldg:WallSurface",
        "bldg:RoofSurface",
        "bldg:OuterCeilingSurface",
        "bldg:OuterFloorSurface",
        "bldg:ClosureSurface",
    ],
    property_groups=[],
    lod_detection=LODDetection(
        lod2=["./bldg:lod2MultiSurface"],
        lod3=["./bldg:lod3MultiSurface"],
        lod4=["./bldg:lod4MultiSurface"],
    ),
    emissions=FeatureEmissions(
        lod2=FeatureEmission(catch_all=[".//bldg:lod2MultiSurface//gml:Polygon"]),
        lod3=FeatureEmission(catch_all=[".//bldg:lod3MultiSurface//gml:Polygon"]),
        lod4=FeatureEmission(catch_all=[".//bldg:lod4MultiSurface//gml:Polygon"]),
    ),
)
