"""建築物モデル (./bldg/)"""

from .base import (
    FeatureEmission,
    FeatureEmissions,
    FeatureProcessingDefinition,
    LODDetection,
    Property,
    PropertyGroup,
)
from .common import facility_id_attribute_attrs

BUILDING = FeatureProcessingDefinition(
    id="Building",
    target_elements=["bldg:Building"],
    lod_detection=LODDetection(
        lod1=["./bldg:lod1Solid"],
        lod2=["./bldg:lod2Solid"],
        lod3=["./bldg:lod3Solid"],
        lod4=["./bldg:lod4Solid", "./bldg:lod4MultiSurface"],
    ),
    property_groups=[
        PropertyGroup(
            base_element=None,
            properties=[
                Property(
                    name="usage",
                    path="./bldg:usage",
                    datatype="[]string",
                    predefined_codelist="Building_usage",
                ),
                Property(
                    name="yearOfConstruction",
                    path="./bldg:yearOfConstruction",
                    datatype="integer",
                ),
                Property(
                    name="yearOfDemolition",
                    path="./bldg:yearOfDemolition",
                    datatype="integer",
                ),
                Property(
                    name="roofType",
                    path="./bldg:roofType",
                    datatype="string",
                    predefined_codelist="Building_roofType",
                ),
                Property(
                    name="measuredHeight",
                    path="./bldg:measuredHeight",
                    datatype="double",
                ),
                Property(
                    name="storeysAboveGround",
                    path="./bldg:storeysAboveGround",
                    datatype="integer",
                ),
                Property(
                    name="storeysBelowGround",
                    path="./bldg:storeysBelowGround",
                    datatype="integer",
                ),
                # Property(
                #     name="address",
                #     path="./bldg:address",
                #     datatype="string",  # TODO: xAL をどう読むか
                # ),
            ],
        ),
        PropertyGroup(
            base_element="./uro:buildingIDAttribute/uro:BuildingIDAttribute",
            properties=[
                Property(
                    name="buildingID",
                    path="./uro:buildingID",
                    datatype="string",
                ),
                Property(
                    name="branchID",
                    path="./uro:branchID",
                    datatype="integer",
                ),
                Property(
                    name="partID",
                    path="./uro:partID",
                    datatype="integer",
                ),
                Property(
                    name="prefecture",
                    path="./uro:prefecture",
                    datatype="string",
                    predefined_codelist="Common_prefecture",
                ),
                Property(
                    name="city",
                    path="./uro:city",
                    datatype="string",
                    predefined_codelist="Common_localPublicAuthorities",
                ),
            ],
        ),
        PropertyGroup(
            base_element="./uro:buildingDetailAttribute/uro:BuildingDetailAttribute",
            properties=[
                Property(
                    name="serialNumberOfBuildingCertification",
                    path="./uro:serialNumberOfBuildingCertification",
                    datatype="string",
                ),
                Property(
                    name="siteArea",
                    path="./uro:siteArea",
                    datatype="double",
                ),
                Property(
                    name="totalFloorArea",
                    path="./uro:totalFloorArea",
                    datatype="double",
                ),
                Property(
                    name="buildingFootprintArea",
                    path="./uro:buildingFootprintArea",
                    datatype="double",
                ),
                Property(
                    name="buildingRoofEdgeArea",
                    path="./uro:buildingRoofEdgeArea",
                    datatype="double",
                ),
                Property(
                    name="developmentArea",
                    path="./uro:developmentArea",
                    datatype="double",
                ),
                Property(
                    name="buildingStructureType",
                    path="./uro:buildingStructureType",
                    datatype="string",
                    predefined_codelist="BuildingDetailAttribute_buildingStructureType",
                ),
                Property(
                    name="buildingStructureOrgType",
                    path="./uro:buildingStructureOrgType",
                    datatype="string",
                ),
                Property(
                    name="fireproofStructureType",
                    path="./uro:fireproofStructureType",
                    datatype="string",
                    predefined_codelist="BuildingDetailAttribute_fireproofStructureType",
                ),
                Property(
                    name="urbanPlanType",
                    path="./uro:urbanPlanType",
                    datatype="string",
                    predefined_codelist="BuildingDetailAttribute_urbanPlanType",
                ),
                Property(
                    name="areaClassificationType",
                    path="./uro:areaClassificationType",
                    datatype="string",
                    predefined_codelist="Common_areaClassificationType",
                ),
                Property(
                    name="districtsAndZonesType",
                    path="./uro:districtsAndZonesType",
                    datatype="[]string",
                    predefined_codelist="Common_districtsAndZonesType",
                ),
                Property(
                    name="landUseType",
                    path="./uro:landUseType",
                    datatype="string",
                    predefined_codelist="Common_landUseType",
                ),
                Property(
                    name="reference",
                    path="./uro:reference",
                    datatype="string",
                ),
                Property(
                    name="majorUsage",
                    path="./uro:majorUsage",
                    datatype="string",
                ),
                Property(
                    name="majorUsage2",
                    path="./uro:majorUsage2",
                    datatype="string",
                ),
                Property(
                    name="orgUsage",
                    path="./uro:orgUsage",
                    datatype="string",
                ),
                Property(
                    name="orgUsage2",
                    path="./uro:orgUsage2",
                    datatype="string",
                ),
                Property(
                    name="detailedUsage",
                    path="./uro:detailedUsage",
                    datatype="string",
                ),
                Property(
                    name="detailedUsage2",
                    path="./uro:detailedUsage2",
                    datatype="string",
                ),
                Property(
                    name="detailedUsage3",
                    path="./uro:detailedUsage3",
                    datatype="string",
                ),
                Property(
                    name="groundFloorUsage",
                    path="./uro:groundFloorUsage",
                    datatype="string",
                ),
                Property(
                    name="secondFloorUsage",
                    path="./uro:secondFloorUsage",
                    datatype="string",
                ),
                Property(
                    name="thirdFloorUsage",
                    path="./uro:thirdFloorUsage",
                    datatype="string",
                ),
                Property(
                    name="basementUsage",
                    path="./uro:basementUsage",
                    datatype="string",
                ),
                Property(
                    name="basementFirstUsage",
                    path="./uro:basementFirstUsage",
                    datatype="string",
                ),
                Property(
                    name="basementSecondUsage",
                    path="./uro:basementSecondUsage",
                    datatype="string",
                ),
                Property(
                    name="vacancy",
                    path="./uro:vacancy",
                    datatype="string",
                    predefined_codelist="BuildingDetailAttribute_vacancy",
                ),
                Property(
                    name="buildingCoverageRate",
                    path="./uro:buildingCoverageRate",
                    datatype="double",
                ),
                Property(
                    name="floorAreaRate",
                    path="./uro:floorAreaRate",
                    datatype="double",
                ),
                Property(
                    name="specifiedBuildingCoverageRate",
                    path="./uro:specifiedBuildingCoverageRate",
                    datatype="double",
                ),
                Property(
                    name="specifiedFloorAreaRate",
                    path="./uro:specifiedFloorAreaRate",
                    datatype="double",
                ),
                Property(
                    name="standardFloorAreaRate",
                    path="./uro:standardFloorAreaRate",
                    datatype="double",
                ),
                Property(
                    name="buidingHeight",
                    path="./uro:buidingHeight",
                    datatype="double",
                ),
                Property(
                    name="eaveHeight",
                    path="./uro:eaveHeight",
                    datatype="double",
                ),
                Property(
                    name="surveyYear",
                    path="./uro:surveyYear",
                    datatype="integer",
                ),
            ],
        ),
        PropertyGroup(
            base_element="./uro:largeCustomerFacilityAttribute/uro:LargeCustomerFacilityAttribute",
            properties=[
                Property(
                    name="class",
                    path="./uro:class",
                    datatype="string",
                    predefined_codelist="LargeCustomerFacilityAttribute_class",
                ),
                Property(
                    name="name",
                    path="./uro:name",
                    datatype="string",
                ),
                Property(
                    name="capacity",
                    path="./uro:capacity",
                    datatype="integer",
                ),
                Property(
                    name="owner",
                    path="./uro:owner",
                    datatype="string",
                ),
                Property(
                    name="totalFloorArea",
                    path="./uro:totalFloorArea",
                    datatype="double",
                ),
                Property(
                    name="totalStoreFloorArea",
                    path="./uro:totalStoreFloorArea",
                    datatype="double",
                ),
                Property(
                    name="inauguralDate",
                    path="./uro:inauguralDate",
                    datatype="date",
                ),
                Property(
                    name="yearOpened",
                    path="./uro:yearOpened",
                    datatype="integer",
                ),
                Property(
                    name="yearClosed",
                    path="./uro:yearClosed",
                    datatype="integer",
                ),
                Property(
                    name="keyTenants",
                    path="./uro:keyTenants",
                    datatype="string",
                ),
                Property(
                    name="availability",
                    path="./uro:availability",
                    datatype="boolean",
                ),
                Property(
                    name="urbanPlanType",
                    path="./uro:urbanPlanType",
                    datatype="string",
                    predefined_codelist="Common_urbanPlanType",
                ),
                Property(
                    name="areaClassificationType",
                    path="./uro:areaClassificationType",
                    datatype="string",
                    predefined_codelist="Common_areaClassificationType",
                ),
                Property(
                    name="districtsAndZonesType",
                    path="./uro:districtsAndZonesType",
                    datatype="[]string",
                    predefined_codelist="Common_districtsAndZonesType",
                ),
                Property(
                    name="landUseType",
                    path="./uro:landUseType",
                    datatype="string",
                    predefined_codelist="Common_landUseType",
                ),
                Property(
                    name="reference",
                    path="./uro:reference",
                    datatype="string",
                ),
                Property(
                    name="note",
                    path="./uro:note",
                    datatype="string",
                ),
                Property(
                    name="surveyYear",
                    path="./uro:surveyYear",
                    datatype="integer",
                ),
            ],
        ),
        PropertyGroup(
            base_element="./uro:buildingDataQualityAttribute/uro:BuildingDataQualityAttribute",
            properties=[
                Property(
                    name="srcScale",
                    path="./uro:srcScale",
                    datatype="[]string",
                    predefined_codelist="BuildingDataQualityAttribute_srcScale",
                ),
                Property(
                    name="geometrySrcDesc",
                    path="./uro:geometrySrcDesc",
                    datatype="[]string",
                    predefined_codelist="BuildingDataQualityAttribute_geometrySrcDesc",
                ),
                Property(
                    name="thematicSrcDesc",
                    path="./uro:thematicSrcDesc",
                    datatype="[]string",
                    predefined_codelist="BuildingDataQualityAttribute_thematicSrcDesc",
                ),
                Property(
                    name="appearanceSrcDesc",
                    path="./uro:appearanceSrcDesc",
                    datatype="[]string",
                    predefined_codelist="BuildingDataQualityAttribute_appearanceSrcDesc",
                ),
                Property(
                    name="lod1HeightType",
                    path="./uro:lod1HeightType",
                    datatype="string",
                    predefined_codelist="BuildingDataQualityAttribute_lod1HeightType",
                ),
                Property(
                    name="lodType",
                    path="./uro:lodType",
                    datatype="[]string",
                ),
            ],
        ),
        PropertyGroup(
            base_element="./uro:bldgFacilityIdAttribute/uro:FacilityIdAttribute",
            properties=facility_id_attribute_attrs,
        ),
        # TODO: uro:buildingDisasterRiskAttribute (入れ子, polymorpohic)
        # TODO: uro:keyValuePairAttribute
        # (TODO: uro:ifcBuildingAttribute)
        # TODO: uro:indoorBuildingAttribute
        # TODO: uro:bldgFacilityTypeAttribute
        # TODO: uro:bldgFacilityAttribute
        # TODO: uro:bldgDmAttribute
    ],
    emissions=FeatureEmissions(
        lod1=FeatureEmission(collect_all=[".//bldg:lod1Solid//gml:Polygon"]),
        lod2=FeatureEmission(
            collect_all=[
                ".//bldg:lod2MultiSurface//gml:Polygon",
                ".//bldg:lod2Geometry//gml:Polygon",
            ],
            only_direct=["./bldg:lod2Solid//gml:Polygon"],
        ),
        lod3=FeatureEmission(
            collect_all=[
                ".//bldg:lod3MultiSurface//gml:Polygon",
                ".//bldg:lod3Geometry//gml:Polygon",
                ".//bldg:lod3Solid//gml:Polygon",
            ],
            only_direct=["./bldg:lod3Solid//gml:Polygon"],
        ),
        lod4=FeatureEmission(
            collect_all=[
                ".//bldg:lod4MultiSurface//gml:Polygon",
                ".//bldg:lod4Geometry//gml:Polygon",
                ".//bldg:lod4Solid//gml:Polygon",
            ],
            only_direct=[
                "./bldg:lod4MultiSurface//gml:Polygon",
                "./bldg:lod4Solid//gml:Polygon",
            ],
        ),
        semantic_parts=[
            ".//bldg:GroundSurface",
            ".//bldg:WallSurface",
            ".//bldg:RoofSurface",
            ".//bldg:OuterCeilingSurface",
            ".//bldg:OuterFloorSurface",
            ".//bldg:ClosureSurface",
            ".//bldg:CeilingSurface",
            ".//bldg:InteriorWallSurface",
            ".//bldg:FloorSurface",
            ".//bldg:BuildingInstallation",
            ".//bldg:IntBuildingInstallation",
            ".//bldg:BuildingFurniture",
            # TODO: 現状、 bldg:Room と bldg:BuildingPart の概念は考慮していない
        ],
    ),
)

BUILDING_BOUNDARY_SURFACE = FeatureProcessingDefinition(
    id="bldg:_BoundarySurface",
    target_elements=[
        "bldg:GroundSurface",
        "bldg:WallSurface",
        "bldg:RoofSurface",
        "bldg:OuterCeilingSurface",
        "bldg:OuterFloorSurface",
        "bldg:ClosureSurface",
        "bldg:CeilingSurface",
        "bldg:InteriorWallSurface",
        "bldg:FloorSurface",
    ],
    property_groups=[],
    lod_detection=LODDetection(
        lod2=["./bldg:lod2MultiSurface"],
        lod3=["./bldg:lod3MultiSurface"],
        lod4=["./bldg:lod4MultiSurface"],
    ),
    emissions=FeatureEmissions(
        lod2=FeatureEmission(
            collect_all=[".//bldg:lod2MultiSurface//gml:Polygon"],
            only_direct=["./bldg:lod2MultiSurface//gml:Polygon"],
        ),
        lod3=FeatureEmission(
            collect_all=[".//bldg:lod3MultiSurface//gml:Polygon"],
            only_direct=["./bldg:lod3MultiSurface//gml:Polygon"],
        ),
        lod4=FeatureEmission(
            collect_all=[".//bldg:lod4MultiSurface//gml:Polygon"],
            only_direct=["./bldg:lod4MultiSurface//gml:Polygon"],
        ),
        semantic_parts=[
            "./bldg:opening/bldg:Door",
            "./bldg:opening/bldg:Window",
        ],
    ),
)

BUILDING_OPENING = FeatureProcessingDefinition(
    id="bldg:_Opening",
    target_elements=[
        "bldg:Window",
        "bldg:Door",
    ],
    property_groups=[
        # TODO: uro:indoorOpeningAttribute
    ],
    lod_detection=LODDetection(
        lod3=["./bldg:lod3MultiSurface"],
        lod4=["./bldg:lod4MultiSurface"],
    ),
    emissions=FeatureEmissions(
        lod3=FeatureEmission(collect_all=[".//bldg:lod3MultiSurface//gml:Polygon"]),
        lod4=FeatureEmission(collect_all=[".//bldg:lod4MultiSurface//gml:Polygon"]),
    ),
)

BUILDING_INSTALLATION = FeatureProcessingDefinition(
    id="BuildingInstallation",
    target_elements=[
        "bldg:BuildingInstallation",
    ],
    property_groups=[
        PropertyGroup(
            base_element=None,
            properties=[
                Property(
                    name="class",
                    path="./bldg:class",
                    datatype="string",
                    predefined_codelist="BuildingInstallation_class",
                ),
                Property(
                    name="function",
                    path="./bldg:function",
                    datatype="[]string",
                    predefined_codelist="BuildingInstallation_function",
                ),
            ],
        )
    ],
    lod_detection=LODDetection(
        lod2=["./bldg:lod2Geometry"],
        lod3=["./bldg:lod3Geometry"],
        lod4=["./bldg:lod4Geometry"],
    ),
    emissions=FeatureEmissions(
        lod2=FeatureEmission(collect_all=[".//bldg:lod2Geometry//gml:Polygon"]),
        lod3=FeatureEmission(collect_all=[".//bldg:lod3Geometry//gml:Polygon"]),
        lod4=FeatureEmission(collect_all=[".//bldg:lod4Geometry//gml:Polygon"]),
    ),
)

BUILDING_INT_INSTALLATION = FeatureProcessingDefinition(
    id="IntBuildingInstallation",
    target_elements=[
        "bldg:IntBuildingInstallation",
    ],
    property_groups=[
        PropertyGroup(
            base_element=None,
            properties=[
                Property(
                    name="class",
                    path="./bldg:class",
                    datatype="string",
                    predefined_codelist="IntBuildingInstallation_class",
                ),
                Property(
                    name="function",
                    path="./bldg:function",
                    datatype="[]string",
                    predefined_codelist="IntBuildingInstallation_function",
                ),
            ],
        ),
        # TODO: uro:indoorInstallationAttribute
    ],
    lod_detection=LODDetection(
        lod2=["./bldg:lod2Geometry"],
        lod3=["./bldg:lod3Geometry"],
        lod4=["./bldg:lod4Geometry"],
    ),
    emissions=FeatureEmissions(
        lod2=FeatureEmission(collect_all=[".//bldg:lod2Geometry//gml:Polygon"]),
        lod3=FeatureEmission(collect_all=[".//bldg:lod3Geometry//gml:Polygon"]),
        lod4=FeatureEmission(collect_all=[".//bldg:lod4Geometry//gml:Polygon"]),
    ),
)


BUILDING_FURNITURE = FeatureProcessingDefinition(
    id="BuildingFurniture",
    target_elements=[
        "bldg:BuildingFurniture",
    ],
    property_groups=[
        PropertyGroup(
            base_element=None,
            properties=[
                Property(
                    name="class",
                    path="./bldg:class",
                    datatype="string",
                    predefined_codelist="BuildingFurniture_class",
                ),
                Property(
                    name="function",
                    path="./bldg:function",
                    datatype="[]string",
                    predefined_codelist="BuildingFurniture_function",
                ),
            ],
        ),
        # TODO: uro:indoorFurnitureAttribute
    ],
    lod_detection=LODDetection(
        lod4=["./bldg:lod4Geometry"],
    ),
    emissions=FeatureEmissions(
        lod4=FeatureEmission(collect_all=[".//bldg:lod4Geometry//gml:Polygon"]),
    ),
)
