"""様々なモデルで共通して使われる定義"""

from .base import Property

# uro:FacilityIdAttribute の属性セット
facility_id_attribute_attrs = [
    Property(
        name="fa:alternativeName",
        path="./uro:alternativeName",
        datatype="[]string",
    ),
    Property(
        name="fa:branchId",
        path="./uro:branchId",
        datatype="string",
    ),
    Property(
        name="fa:city",
        path="./uro:city",
        datatype="[]string",
        predefined_codelist=None,
    ),
    Property(
        name="fa:endPost",
        path="./uro:endPost",
        datatype="string",
    ),
    Property(
        name="fa:uro:id",
        path="./uro:id",
        datatype="string",
    ),
    Property(
        name="fa:leftDistance",
        path="./uro:leftDistance",
        datatype="double",
    ),
    Property(
        name="fa:leftDownstreamDistance",
        path="./uro:leftDownstreamDistance",
        datatype="double",
    ),
    Property(
        name="fa:leftDownstreamPost",
        path="./uro:leftDownstreamPost",
        datatype="double",
    ),
    Property(
        name="fa:leftPost",
        path="./uro:leftPost",
        datatype="double",
    ),
    Property(
        name="fa:leftUpstreamDistance",
        path="./uro:leftUpstreamDistance",
        datatype="double",
    ),
    Property(
        name="fa:leftUpstreamPost",
        path="./uro:leftUpstreamPost",
        datatype="double",
    ),
    Property(
        name="fa:partId",
        path="./uro:partId",
        datatype="string",
    ),
    Property(
        name="fa:prefecture",
        path="./uro:prefecture",
        datatype="[]string",
        predefined_codelist=None,
    ),
    Property(
        name="fa:rightDistance",
        path="./uro:rightDistance",
        datatype="double",
    ),
    Property(
        name="fa:rightDownstreamDistance",
        path="./uro:rightDownstreamDistance",
        datatype="double",
    ),
    Property(
        name="fa:rightDownstreamPost",
        path="./uro:rightDownstreamPost",
        datatype="double",
    ),
    Property(
        name="fa:rightPost",
        path="./uro:rightPost",
        datatype="double",
    ),
    Property(
        name="fa:rightUpstreamDistance",
        path="./uro:rightUpstreamDistance",
        datatype="double",
    ),
    Property(
        name="fa:rightUpstreamPost",
        path="./uro:rightUpstreamPost",
        datatype="double",
    ),
    Property(
        name="fa:riverCode",
        path="./uro:riverCode",
        datatype="string",
    ),
    Property(
        name="fa:riverName",
        path="./uro:riverName",
        datatype="string",
        predefined_codelist=None,
    ),
    Property(
        name="fa:route",
        path="./uro:route",
        datatype="string",
    ),
    Property(
        name="fa:sideType",
        path="./uro:sideType",
        datatype="string",
        predefined_codelist=None,
    ),
    Property(
        name="fa:startLat",
        path="./uro:startLat",
        datatype="double",
    ),
    Property(
        name="fa:startLong",
        path="./uro:startLong",
        datatype="double",
    ),
    Property(
        name="fa:startPost",
        path="./uro:startPost",
        datatype="string",
    ),
]
