"""交通モデル 道路 (./tran/) 鉄道 (./rwy/) 徒歩道 (./trk/) 広場 (./squr/) 航路 (./wwy/)"""

# FIXME: 徒歩道、広場、航路の属性値

from .base import (
    FeatureEmission,
    FeatureEmissions,
    FeatureProcessingDefinition,
    LODDetection,
    Property,
    PropertyGroup,
)
from .common import facility_id_attribute_attrs

_transportation_data_quality_attribute = [
    Property(
        name="srcScale",
        path="./uro:srcScale",
        datatype="[]string",
        predefined_codelist="RoadDataQualityAttribute_srcScale",
    ),
    Property(
        name="geometrySrcDesc",
        path="./uro:geometrySrcDesc",
        datatype="[]string",
        predefined_codelist="RoadDataQualityAttribute_geometrySrcDesc",
    ),
    Property(
        name="thematicSrcDesc",
        path="./uro:thematicSrcDesc",
        datatype="[]string",
        predefined_codelist="RoadDataQualityAttribute_thematicSrcDesc",
    ),
    Property(
        name="appearanceSrcDesc",
        path="./uro:appearanceSrcDesc",
        datatype="[]string",
        predefined_codelist="RoadDataQualityAttribute_appearanceSrcDesc",
    ),
    Property(
        name="lodType",
        path="./uro:lodType",
        datatype="[]string",
        predefined_codelist="Road_lodType",
    ),
]

ROAD = FeatureProcessingDefinition(
    id="Road",
    target_elements=["tran:Road"],
    lod_detection=LODDetection(
        lod1=["./tran:lod1MultiSurface"],
        lod2=["./tran:lod2MultiSurface"],
        lod3=["./tran:lod3MultiSurface"],
        lod4=["./tran:lod4MultiSurface"],
    ),
    property_groups=[
        PropertyGroup(
            base_element=None,
            properties=[
                Property(
                    name="class",
                    path="./tran:class",
                    datatype="string",
                    predefined_codelist="TransportationComplex_class",
                ),
                Property(
                    name="function",
                    path="./tran:function",
                    datatype="[]string",
                    predefined_codelist="Road_function",
                ),
                Property(
                    name="usage",
                    path="./tran:usage",
                    datatype="[]string",
                    predefined_codelist="Road_usage",
                ),
            ],
        ),
        PropertyGroup(
            base_element="./uro:roadStructureAttribute/uro:RoadStructureAttribute",
            properties=[
                Property(
                    name="width",
                    path="./uro:width",
                    datatype="double",
                ),
                Property(
                    name="widthType",
                    path="./uro:widthType",
                    datatype="string",
                    predefined_codelist="RoadStructureAttribute_widthType",
                ),
                Property(
                    name="numberOfLanes",
                    path="./uro:numberOfLanes",
                    datatype="integer",
                ),
                Property(
                    name="sectionType",
                    path="./uro:sectionType",
                    datatype="string",
                    predefined_codelist="RoadStructureAttribute_sectionType",
                ),
            ],
        ),
        PropertyGroup(
            base_element="./uro:trafficVolumeAttribute/uro:TrafficVolumeAttribute",
            properties=[
                Property(
                    name="averageInboundTravelSpeedInCongestion",
                    path="./uro:averageInboundTravelSpeedInCongestion",
                    datatype="double",
                ),
                Property(
                    name="averageInboundTravelSpeedNotCongestion",
                    path="./uro:averageInboundTravelSpeedNotCongestion",
                    datatype="double",
                ),
                Property(
                    name="averageOutboundTravelSpeedInCongestion",
                    path="./uro:averageOutboundTravelSpeedInCongestion",
                    datatype="double",
                ),
                Property(
                    name="averageOutboundTravelSpeedNotCongestion",
                    path="./uro:averageOutboundTravelSpeedNotCongestion",
                    datatype="double",
                ),
                Property(
                    name="averageTravelSpeedInCongestion",
                    path="./uro:averageTravelSpeedInCongestion",
                    datatype="double",
                ),
                Property(
                    name="congestionRate",
                    path="./uro:congestionRate",
                    datatype="double",
                ),
                Property(
                    name="largeVehicleRate",
                    path="./uro:largeVehicleRate",
                    datatype="double",
                ),
                Property(
                    name="observationPointName",
                    path="./uro:observationPointName",
                    datatype="string",
                ),
                Property(
                    name="reference",
                    path="./uro:reference",
                    datatype="string",
                ),
                Property(
                    name="routeName",
                    path="./uro:routeName",
                    datatype="string",
                ),
                Property(
                    name="sectionID",
                    path="./uro:sectionID",
                    datatype="string",
                ),
                Property(
                    name="surveyYear",
                    path="./uro:surveyYear",
                    datatype="integer",
                ),
                Property(
                    name="weekday12hourTrafficVolume",
                    path="./uro:weekday12hourTrafficVolume",
                    datatype="integer",
                ),
                Property(
                    name="weekday24hourTrafficVolume",
                    path="./uro:weekday24hourTrafficVolume",
                    datatype="integer",
                ),
            ],
        ),
        PropertyGroup(
            base_element="./uro:tranFacilityIdAttribute/uro:FacilityIdAttribute",
            properties=facility_id_attribute_attrs,
        ),
        PropertyGroup(
            base_element="./uro:tranDataQualityAttribute/uro:TransportationDataQualityAttribute",
            properties=_transportation_data_quality_attribute,
        )
        # TODO: uro:tranFacilityTypeAttribute
        # TODO: uro:tranFacilityAttribute
        # TODO: uro:tranDmAttribute
    ],
    emissions=FeatureEmissions(
        lod1=FeatureEmission(
            collect_all=["./tran:lod1MultiSurface//gml:Polygon"],
            only_direct=["./tran:lod1MultiSurface//gml:Polygon"],
        ),
        lod2=FeatureEmission(
            collect_all=[".//tran:lod2MultiSurface//gml:Polygon"],
            only_direct=["./tran:lod2MultiSurface//gml:Polygon"],
        ),
        lod3=FeatureEmission(
            collect_all=[".//tran:lod3MultiSurface//gml:Polygon"],
            only_direct=["./tran:lod3MultiSurface//gml:Polygon"],
        ),
        lod4=FeatureEmission(
            collect_all=[".//tran:lod4MultiSurface//gml:Polygon"],
            only_direct=["./tran:lod4MultiSurface//gml:Polygon"],
        ),
        semantic_parts=[
            "./tran:trafficArea/tran:TrafficArea",
            "./tran:auxiliaryTrafficArea/tran:AuxiliaryTrafficArea",
        ],
    ),
)

RAILWAY = FeatureProcessingDefinition(
    id="Railway",
    target_elements=["tran:Railway"],
    lod_detection=LODDetection(
        lod1=["./tran:lod1MultiSurface"],
        lod2=["./tran:lod2MultiSurface"],
        lod3=["./tran:lod3MultiSurface"],
        lod4=["./tran:lod4MultiSurface"],
    ),
    property_groups=[
        PropertyGroup(
            base_element=None,
            properties=[
                Property(
                    name="class",
                    path="./tran:class",
                    datatype="string",
                    predefined_codelist="TransportationComplex_class",
                ),
                Property(
                    name="function",
                    path="./tran:function",
                    datatype="[]string",
                    predefined_codelist="Railway_function",
                ),
            ],
        ),
        PropertyGroup(
            base_element="./uro:railwayRouteAttribute/uro:RailwayRouteAttribute",
            properties=[
                Property(
                    name="operatorType",
                    path="./uro:operatorType",
                    datatype="string",
                    predefined_codelist="RailwayRouteAttribute_operatorType",
                ),
                Property(
                    name="operator",
                    path="./uro:operator",
                    datatype="string",
                ),
                Property(
                    name="alternativeName",
                    path="./uro:alternativeName",
                    datatype="[]string",
                ),
                Property(
                    name="startStation",
                    path="./uro:startStation",
                    datatype="string",
                ),
                Property(
                    name="endStation",
                    path="./uro:endStation",
                    datatype="string",
                ),
            ],
        ),
        PropertyGroup(
            base_element="./uro:tranFacilityIdAttribute/uro:FacilityIdAttribute",
            properties=facility_id_attribute_attrs,
        ),
        PropertyGroup(
            base_element="./uro:tranDataQualityAttribute/uro:TransportationDataQualityAttribute",
            properties=_transportation_data_quality_attribute,
        )
        # TODO: uro:tranFacilityTypeAttribute
        # TODO: uro:tranFacilityAttribute
        # TODO: uro:tranDmAttribute
    ],
    emissions=FeatureEmissions(
        lod1=FeatureEmission(
            collect_all=["./tran:lod1MultiSurface//gml:Polygon"],
            only_direct=["./tran:lod1MultiSurface//gml:Polygon"],
        ),
        lod2=FeatureEmission(
            collect_all=[".//tran:lod2MultiSurface//gml:Polygon"],
            only_direct=["./tran:lod2MultiSurface//gml:Polygon"],
        ),
        lod3=FeatureEmission(
            collect_all=[".//tran:lod3MultiSurface//gml:Polygon"],
            only_direct=["./tran:lod3MultiSurface//gml:Polygon"],
        ),
        lod4=FeatureEmission(
            collect_all=[".//tran:lod4MultiSurface//gml:Polygon"],
            only_direct=["./tran:lod4MultiSurface//gml:Polygon"],
        ),
        semantic_parts=[
            "./tran:trafficArea/tran:TrafficArea",
            "./tran:auxiliaryTrafficArea/tran:AuxiliaryTrafficArea",
        ],
    ),
)

TRACK = FeatureProcessingDefinition(
    id="Track",
    target_elements=["tran:Track"],
    lod_detection=LODDetection(
        lod1=["./tran:lod1MultiSurface"],
        lod2=["./tran:lod2MultiSurface"],
        lod3=["./tran:lod3MultiSurface"],
        lod4=["./tran:lod4MultiSurface"],
    ),
    property_groups=[
        PropertyGroup(
            base_element=None,
            properties=[
                Property(
                    name="class",
                    path="./tran:class",
                    datatype="string",
                    predefined_codelist="TransportationComplex_class",
                ),
                Property(
                    name="function",
                    path="./tran:function",
                    datatype="[]string",
                    predefined_codelist="Track_function",
                ),
            ],
        ),
        PropertyGroup(
            base_element="./uro:trackAttribute/uro:TrackAttribute",
            properties=[
                Property(
                    name="adminType",
                    path="./uro:adminType",
                    datatype="string",
                    predefined_codelist="TrackAttribute_adminType",
                ),
                Property(
                    name="alternativeName",
                    path="./uro:alternativeName",
                    datatype="[]string",
                ),
                Property(
                    name="isTollRoad",
                    path="./uro:isTollRoad",
                    datatype="boolean",
                ),
                Property(
                    name="relativeLevel",
                    path="./uro:relativeLevel",
                    datatype="integer",
                ),
                Property(
                    name="separator",
                    path="./uro:separator",
                    datatype="double",
                ),
                Property(
                    name="structureType",
                    path="./uro:structureType",
                    datatype="string",
                    predefined_codelist="TrackAttribute_structureType",
                ),
                Property(
                    name="widthType",
                    path="./uro:widthType",
                    datatype="string",
                    predefined_codelist="TrackAttribute_widthType",
                ),
            ],
        ),
        PropertyGroup(
            base_element="./uro:tranFacilityIdAttribute/uro:FacilityIdAttribute",
            properties=facility_id_attribute_attrs,
        ),
        PropertyGroup(
            base_element="./uro:tranDataQualityAttribute/uro:TransportationDataQualityAttribute",
            properties=_transportation_data_quality_attribute,
        )
        # TODO: uro:tranFacilityTypeAttribute
        # TODO: uro:tranFacilityAttribute
        # TODO: uro:tranDmAttribute
    ],
    emissions=FeatureEmissions(
        lod1=FeatureEmission(
            collect_all=["./tran:lod1MultiSurface//gml:Polygon"],
            only_direct=["./tran:lod1MultiSurface//gml:Polygon"],
        ),
        lod2=FeatureEmission(
            collect_all=[".//tran:lod2MultiSurface//gml:Polygon"],
            only_direct=["./tran:lod2MultiSurface//gml:Polygon"],
        ),
        lod3=FeatureEmission(
            collect_all=[".//tran:lod3MultiSurface//gml:Polygon"],
            only_direct=["./tran:lod3MultiSurface//gml:Polygon"],
        ),
        lod4=FeatureEmission(
            collect_all=[".//tran:lod4MultiSurface//gml:Polygon"],
            only_direct=["./tran:lod4MultiSurface//gml:Polygon"],
        ),
        semantic_parts=[
            "./tran:trafficArea/tran:TrafficArea",
            "./tran:auxiliaryTrafficArea/tran:AuxiliaryTrafficArea",
        ],
    ),
)

_square_urban_plan_attribute_attrs = [
    Property(
        name="areaCompleted",
        path="./uro:areaCompleted",
        datatype="double",
    ),
    Property(
        name="areaImproved",
        path="./uro:areaImproved",
        datatype="double",
    ),
    Property(
        name="areaInService",
        path="./uro:areaInService",
        datatype="double",
    ),
    Property(
        name="areaPlanned",
        path="./uro:areaPlanned",
        datatype="double",
    ),
    Property(
        name="city",
        path="./uro:city",
        datatype="string",
        predefined_codelist="Common_localPublicAuthorities",
    ),
    Property(
        name="dateOfDecision",
        path="./uro:dateOfDecision",
        datatype="date",
    ),
    Property(
        name="dateOfRevision",
        path="./uro:dateOfRevision",
        datatype="date",
    ),
    Property(
        name="enforcer",
        path="./uro:enforcer",
        datatype="[]string",
    ),
    Property(
        name="isAuthorized",
        path="./uro:isAuthorized",
        datatype="boolean",
    ),
    Property(
        name="isCompleted",
        path="./uro:isCompleted",
        datatype="boolean",
    ),
    Property(
        name="note",
        path="./uro:note",
        datatype="string",
    ),
    Property(
        name="numberOfBerthsInService",
        path="./uro:numberOfBerthsInService",
        datatype="integer",
    ),
    Property(
        name="numberOfBerthsPlanned",
        path="./uro:numberOfBerthsPlanned",
        datatype="integer",
    ),
    Property(
        name="prefecture",
        path="./uro:prefecture",
        datatype="string",
        predefined_codelist="Common_localPublicAuthorities",
    ),
    Property(
        name="projectEndDate",
        path="./uro:projectEndDate",
        datatype="date",
    ),
    Property(
        name="projectStartDate",
        path="./uro:projectStartDate",
        datatype="date",
    ),
    Property(
        name="purpose",
        path="./uro:purpose",
        datatype="string",
    ),
    Property(
        name="railwayType",
        path="./uro:railwayType",
        datatype="[]string",
        predefined_codelist=None,
    ),
    Property(
        name="remarks",
        path="./uro:remarks",
        datatype="string",
    ),
    Property(
        name="route",
        path="./uro:route",
        datatype="[]string",
    ),
    Property(
        name="station",
        path="./uro:station",
        datatype="[]string",
    ),
    Property(
        name="status",
        path="./uro:status",
        datatype="string",
        predefined_codelist=None,
    ),
    Property(
        name="structure",
        path="./uro:structure",
        datatype="string",
    ),
    Property(
        name="terminalType",
        path="./uro:terminalType",
        datatype="string",
        predefined_codelist=None,
    ),
    Property(
        name="urbanPlanningAreaName",
        path="./uro:urbanPlanningAreaName",
        datatype="string",
    ),
    Property(
        name="userType",
        path="./uro:userType",
        datatype="string",
        predefined_codelist=None,
    ),
]

SQUARE = FeatureProcessingDefinition(
    id="Square",
    target_elements=["tran:Square"],
    lod_detection=LODDetection(
        lod1=["./tran:lod1MultiSurface"],
        lod2=["./tran:lod2MultiSurface"],
        lod3=["./tran:lod3MultiSurface"],
        lod4=["./tran:lod4MultiSurface"],
    ),
    property_groups=[
        PropertyGroup(
            base_element=None,
            properties=[
                Property(
                    name="class",
                    path="./tran:class",
                    datatype="string",
                    predefined_codelist="TransportationComplex_class",
                ),
                Property(
                    name="function",
                    path="./tran:function",
                    datatype="[]string",
                    predefined_codelist="Square_function",
                ),
            ],
        ),
        PropertyGroup(
            base_element="./uro:railwayRouteAttribute/uro:SquareUrbanPlanAttribute",
            properties=_square_urban_plan_attribute_attrs,
        ),
        PropertyGroup(
            base_element="./uro:railwayRouteAttribute/uro:StationSquareAttribute",
            properties=_square_urban_plan_attribute_attrs,
        ),
        PropertyGroup(
            base_element="./uro:railwayRouteAttribute/uro:TerminalAttribute",
            properties=_square_urban_plan_attribute_attrs,
        ),
        PropertyGroup(
            base_element="./uro:tranFacilityIdAttribute/uro:FacilityIdAttribute",
            properties=facility_id_attribute_attrs,
        ),
        PropertyGroup(
            base_element="./uro:tranDataQualityAttribute/uro:TransportationDataQualityAttribute",
            properties=_transportation_data_quality_attribute,
        )
        # TODO: uro:tranFacilityTypeAttribute
        # TODO: uro:tranFacilityAttribute
        # TODO: uro:tranDmAttribute
    ],
    emissions=FeatureEmissions(
        lod1=FeatureEmission(
            collect_all=["./tran:lod1MultiSurface//gml:Polygon"],
            only_direct=["./tran:lod1MultiSurface//gml:Polygon"],
        ),
        lod2=FeatureEmission(
            collect_all=[".//tran:lod2MultiSurface//gml:Polygon"],
            only_direct=["./tran:lod2MultiSurface//gml:Polygon"],
        ),
        lod3=FeatureEmission(
            collect_all=[".//tran:lod3MultiSurface//gml:Polygon"],
            only_direct=["./tran:lod3MultiSurface//gml:Polygon"],
        ),
        lod4=FeatureEmission(
            collect_all=[".//tran:lod4MultiSurface//gml:Polygon"],
            only_direct=["./tran:lod4MultiSurface//gml:Polygon"],
        ),
        semantic_parts=[
            "./tran:trafficArea/tran:TrafficArea",
            "./tran:auxiliaryTrafficArea/tran:AuxiliaryTrafficArea",
        ],
    ),
)

WATERWAY = FeatureProcessingDefinition(
    id="Waterway",
    target_elements=[
        "uro2:Waterway",
        "uro3:Waterway",
    ],
    lod_detection=LODDetection(
        lod1=["./tran:lod1MultiSurface"],
        lod2=["./tran:lod2MultiSurface"],
        lod3=["./tran:lod3MultiSurface"],
        lod4=["./tran:lod4MultiSurface"],
    ),
    property_groups=[
        PropertyGroup(
            base_element=None,
            properties=[
                Property(
                    name="class",
                    path="./tran:class",
                    datatype="string",
                    predefined_codelist="TransportationComplex_class",
                ),
                Property(
                    name="function",
                    path="./tran:function",
                    datatype="[]string",
                    predefined_codelist="Waterway_function",
                ),
            ],
        ),
        PropertyGroup(
            base_element="./uro:watewayDetailAttribute/uro:WaterwayDetailAttribute",
            properties=[
                Property(
                    name="length",
                    path="./uro:length",
                    datatype="double",
                ),
                Property(
                    name="maximumWidth",
                    path="./uro:maximumWidth",
                    datatype="double",
                ),
                Property(
                    name="minimumWidth",
                    path="./uro:minimumWidth",
                    datatype="double",
                ),
                Property(
                    name="navigation",
                    path="./uro:navigation",
                    datatype="string",
                ),
                Property(
                    name="plannedDepth",
                    path="./uro:plannedDepth",
                    datatype="double",
                ),
                Property(
                    name="routeDirection",
                    path="./uro:routeDirection",
                    datatype="string",
                    predefined_codelist=None,
                ),
                Property(
                    name="routeID",
                    path="./uro:routeID",
                    datatype="integer",
                ),
                Property(
                    name="speedLimit",
                    path="./uro:speedLimit",
                    datatype="double",
                ),
                Property(
                    name="targetShipType",
                    path="./uro:targetShipType",
                    datatype="[]string",
                ),
            ],
        ),
        PropertyGroup(
            base_element="./uro:tranFacilityIdAttribute/uro:FacilityIdAttribute",
            properties=facility_id_attribute_attrs,
        ),
        PropertyGroup(
            base_element="./uro:tranDataQualityAttribute/uro:TransportationDataQualityAttribute",
            properties=_transportation_data_quality_attribute,
        )
        # TODO: uro:tranFacilityTypeAttribute
        # TODO: uro:tranFacilityAttribute
        # TODO: uro:tranDmAttribute
    ],
    emissions=FeatureEmissions(
        lod1=FeatureEmission(
            collect_all=["./tran:lod1MultiSurface//gml:Polygon"],
            only_direct=["./tran:lod1MultiSurface//gml:Polygon"],
        ),
        lod2=FeatureEmission(
            collect_all=[".//tran:lod2MultiSurface//gml:Polygon"],
            only_direct=["./tran:lod2MultiSurface//gml:Polygon"],
        ),
        lod3=FeatureEmission(
            collect_all=[".//tran:lod3MultiSurface//gml:Polygon"],
            only_direct=["./tran:lod3MultiSurface//gml:Polygon"],
        ),
        lod4=FeatureEmission(
            collect_all=[".//tran:lod4MultiSurface//gml:Polygon"],
            only_direct=["./tran:lod4MultiSurface//gml:Polygon"],
        ),
        semantic_parts=[
            "./tran:trafficArea/tran:TrafficArea",
            "./tran:auxiliaryTrafficArea/tran:AuxiliaryTrafficArea",
        ],
    ),
)

# TrafficArea, AuxiliaryTrafficArea を扱う
# これらは Road, Railway, Track, Square (いずれもLOD2-4) の子として使われる
TRAFFIC_AREA = FeatureProcessingDefinition(
    id="TrafficArea",
    target_elements=["tran:TrafficArea", "tran:AuxiliaryTrafficArea"],
    property_groups=[
        PropertyGroup(
            base_element=None,
            properties=[
                Property(
                    name="function",
                    path="./tran:function",
                    datatype="[]string",
                    predefined_codelist="TrafficArea_function",
                ),
                Property(
                    name="surfaceMaterial",
                    path="./tran:surfaceMaterial",
                    datatype="string",
                    predefined_codelist="TrafficArea_surfaceMaterial",
                ),
            ],
        ),
        # uro:TrafficAreaStructureAttribute (Road)
        PropertyGroup(
            base_element="./uro:trafficAreaStructureAttribute/uro:TrafficAreaStructureAttribute",
            properties=[
                Property(
                    name="numberOfLanes",
                    path="./uro:numberOfLanes",
                    datatype="integer",
                ),
            ],
        ),
        # uro:RailwayTrackAttribute (Railway)
        PropertyGroup(
            base_element="./uro:railwayTrackAttribute/uro:RailwayTrackAttribute",
            properties=[
                Property(
                    name="routeName",
                    path="./uro:routeName",
                    datatype="string",
                ),
                Property(
                    name="directionType",
                    path="./uro:directionType",
                    datatype="string",
                    predefined_codelist="RailwayTrackAttribute_directionType",
                ),
                Property(
                    name="trackType",
                    path="./uro:trackType",
                    datatype="string",
                    predefined_codelist="RailwayTrackAttribute_trackType",
                ),
                Property(
                    name="startPost",
                    path="./uro:startPost",
                    datatype="string",
                ),
                Property(
                    name="endPost",
                    path="./uro:endPost",
                    datatype="string",
                ),
                Property(
                    name="alignmentType",
                    path="./uro:alignmentType",
                    datatype="string",
                    predefined_codelist="RailwayTrackAttribute_alignmentType",
                ),
            ],
        ),
    ],
    lod_detection=LODDetection(
        lod2=["./tran:lod2MultiSurface"],
        lod3=["./tran:lod3MultiSurface"],
        lod4=["./tran:lod4MultiSurface"],
    ),
    emissions=FeatureEmissions(
        lod2=FeatureEmission(collect_all=["./tran:lod2MultiSurface//gml:Polygon"]),
        lod3=FeatureEmission(collect_all=["./tran:lod3MultiSurface//gml:Polygon"]),
        lod4=FeatureEmission(collect_all=["./tran:lod4MultiSurface//gml:Polygon"]),
    ),
)
