"""交通モデル 道路 (./tran/) 鉄道 (./rwy/) 徒歩道 (./trk/) 広場 (./squr/) 航路 (./wwy/)

ただし 徒歩道・広場・航路 については、仕様上定められているものの、具体的な事例は存在しない。
"""

from .base import (
    FeatureEmission,
    FeatureEmissions,
    FeatureProcessingDefinition,
    LODDetection,
    Property,
    PropertyGroup,
)
from .common import facility_id_attribute_attrs

_transportation_data_quality_attribute = [
    Property(
        name="srcScale",
        path="./uro:srcScale",
        datatype="[]string",
        predefined_codelist="RoadDataQualityAttribute_srcScale",
    ),
    Property(
        name="geometrySrcDesc",
        path="./uro:geometrySrcDesc",
        datatype="[]string",
        predefined_codelist="RoadDataQualityAttribute_geometrySrcDesc",
    ),
    Property(
        name="thematicSrcDesc",
        path="./uro:thematicSrcDesc",
        datatype="[]string",
        predefined_codelist="RoadDataQualityAttribute_thematicSrcDesc",
    ),
    Property(
        name="appearanceSrcDesc",
        path="./uro:appearanceSrcDesc",
        datatype="[]string",
        predefined_codelist="RoadDataQualityAttribute_appearanceSrcDesc",
    ),
    Property(
        name="lodType",
        path="./uro:lodType",
        datatype="[]string",
        predefined_codelist="Road_lodType",
    ),
]

ROAD = FeatureProcessingDefinition(
    id="Road",
    target_elements=["tran:Road"],
    lod_detection=LODDetection(
        lod1=["./tran:lod1MultiSurface"],
        lod2=["./tran:lod2MultiSurface"],
        lod3=["./tran:lod3MultiSurface"],
        lod4=["./tran:lod4MultiSurface"],
    ),
    property_groups=[
        PropertyGroup(
            base_element=None,
            properties=[
                Property(
                    name="class",
                    path="./tran:class",
                    datatype="string",
                    predefined_codelist="TransportationComplex_class",
                ),
                Property(
                    name="function",
                    path="./tran:function",
                    datatype="[]string",
                    predefined_codelist="Road_function",
                ),
                Property(
                    name="usage",
                    path="./tran:usage",
                    datatype="[]string",
                    predefined_codelist="Road_usage",
                ),
            ],
        ),
        PropertyGroup(
            base_element="./uro:roadStructureAttribute/uro:RoadStructureAttribute",
            properties=[
                Property(
                    name="width",
                    path="./uro:width",
                    datatype="double",
                ),
                Property(
                    name="widthType",
                    path="./uro:widthType",
                    datatype="string",
                    predefined_codelist="RoadStructureAttribute_widthType",
                ),
                Property(
                    name="numberOfLanes",
                    path="./uro:numberOfLanes",
                    datatype="integer",
                ),
                Property(
                    name="sectionType",
                    path="./uro:sectionType",
                    datatype="string",
                    predefined_codelist="RoadStructureAttribute_sectionType",
                ),
            ],
        ),
        PropertyGroup(
            base_element="./uro:tranFacilityIdAttribute/uro:FacilityIdAttribute",
            properties=facility_id_attribute_attrs,
        ),
        PropertyGroup(
            base_element="./uro:trafficVolumeAttribute/uro:TrafficVolumeAttribute",
            properties=[
                Property(
                    name="averageInboundTravelSpeedInCongestion",
                    path="./uro:averageInboundTravelSpeedInCongestion",
                    datatype="double",
                ),
                Property(
                    name="averageInboundTravelSpeedNotCongestion",
                    path="./uro:averageInboundTravelSpeedNotCongestion",
                    datatype="double",
                ),
                Property(
                    name="averageOutboundTravelSpeedInCongestion",
                    path="./uro:averageOutboundTravelSpeedInCongestion",
                    datatype="double",
                ),
                Property(
                    name="averageOutboundTravelSpeedNotCongestion",
                    path="./uro:averageOutboundTravelSpeedNotCongestion",
                    datatype="double",
                ),
                Property(
                    name="averageTravelSpeedInCongestion",
                    path="./uro:averageTravelSpeedInCongestion",
                    datatype="double",
                ),
                Property(
                    name="congestionRate",
                    path="./uro:congestionRate",
                    datatype="double",
                ),
                Property(
                    name="largeVehicleRate",
                    path="./uro:largeVehicleRate",
                    datatype="double",
                ),
                Property(
                    name="observationPointName",
                    path="./uro:observationPointName",
                    datatype="string",
                ),
                Property(
                    name="reference",
                    path="./uro:reference",
                    datatype="string",
                ),
                Property(
                    name="routeName",
                    path="./uro:routeName",
                    datatype="string",
                ),
                Property(
                    name="sectionID",
                    path="./uro:sectionID",
                    datatype="string",
                ),
                Property(
                    name="surveyYear",
                    path="./uro:surveyYear",
                    datatype="integer",
                ),
                Property(
                    name="weekday12hourTrafficVolume",
                    path="./uro:weekday12hourTrafficVolume",
                    datatype="integer",
                ),
                Property(
                    name="weekday24hourTrafficVolume",
                    path="./uro:weekday24hourTrafficVolume",
                    datatype="integer",
                ),
            ],
        ),
        PropertyGroup(
            base_element="./uro:tranDataQualityAttribute/uro:TransportationDataQualityAttribute",
            properties=_transportation_data_quality_attribute,
        )
        # TODO: uro:tranFacilityTypeAttribute
        # TODO: uro:tranFacilityAttribute
        # TODO: uro:tranDmAttribute
    ],
    emissions=FeatureEmissions(
        lod1=FeatureEmission(
            collect_all=["./tran:lod1MultiSurface//gml:Polygon"],
            only_direct=["./tran:lod1MultiSurface//gml:Polygon"],
        ),
        lod2=FeatureEmission(
            collect_all=[".//tran:lod2MultiSurface//gml:Polygon"],
            only_direct=["./tran:lod2MultiSurface//gml:Polygon"],
        ),
        lod3=FeatureEmission(
            collect_all=[".//tran:lod3MultiSurface//gml:Polygon"],
            only_direct=["./tran:lod3MultiSurface//gml:Polygon"],
        ),
        lod4=FeatureEmission(
            collect_all=[".//tran:lod4MultiSurface//gml:Polygon"],
            only_direct=["./tran:lod4MultiSurface//gml:Polygon"],
        ),
        semantic_parts=[
            "./tran:trafficArea/tran:TrafficArea",
            "./tran:auxiliaryTrafficArea/tran:AuxiliaryTrafficArea",
        ],
    ),
)

RAILWAY = FeatureProcessingDefinition(
    id="Railway",
    target_elements=["tran:Railway"],
    lod_detection=LODDetection(
        lod1=["./tran:lod1MultiSurface"],
        lod2=["./tran:lod2MultiSurface"],
        lod3=["./tran:lod3MultiSurface"],
        lod4=["./tran:lod4MultiSurface"],
    ),
    property_groups=[
        PropertyGroup(
            base_element=None,
            properties=[
                Property(
                    name="class",
                    path="./tran:class",
                    datatype="string",
                    predefined_codelist="TransportationComplex_class",
                ),
                Property(
                    name="function",
                    path="./tran:function",
                    datatype="[]string",
                    predefined_codelist="Railway_function",
                ),
            ],
        ),
        PropertyGroup(
            base_element="./uro:railwayRouteAttribute/uro:RailwayRouteAttribute",
            properties=[
                Property(
                    name="operatorType",
                    path="./uro:operatorType",
                    datatype="string",
                    predefined_codelist="RailwayRouteAttribute_operatorType",
                ),
                Property(
                    name="operator",
                    path="./uro:operator",
                    datatype="string",
                ),
                Property(
                    name="alternativeName",
                    path="./uro:alternativeName",
                    datatype="[]string",
                ),
                Property(
                    name="startStation",
                    path="./uro:startStation",
                    datatype="string",
                ),
                Property(
                    name="endStation",
                    path="./uro:endStation",
                    datatype="string",
                ),
            ],
        ),
        PropertyGroup(
            base_element="./uro:tranDataQualityAttribute/uro:TransportationDataQualityAttribute",
            properties=_transportation_data_quality_attribute,
        )
        # TODO: uro:tranFacilityTypeAttribute
        # TODO: uro:tranFacilityAttribute
        # TODO: uro:tranDmAttribute
    ],
    emissions=FeatureEmissions(
        lod1=FeatureEmission(
            collect_all=["./tran:lod1MultiSurface//gml:Polygon"],
            only_direct=["./tran:lod1MultiSurface//gml:Polygon"],
        ),
        lod2=FeatureEmission(
            collect_all=[".//tran:lod2MultiSurface//gml:Polygon"],
            only_direct=["./tran:lod2MultiSurface//gml:Polygon"],
        ),
        lod3=FeatureEmission(
            collect_all=[".//tran:lod3MultiSurface//gml:Polygon"],
            only_direct=["./tran:lod3MultiSurface//gml:Polygon"],
        ),
        lod4=FeatureEmission(
            collect_all=[".//tran:lod4MultiSurface//gml:Polygon"],
            only_direct=["./tran:lod4MultiSurface//gml:Polygon"],
        ),
        semantic_parts=[
            "./tran:trafficArea/tran:TrafficArea",
            "./tran:auxiliaryTrafficArea/tran:AuxiliaryTrafficArea",
        ],
    ),
)

# TrafficArea, AuxiliaryTrafficArea を扱う
# これらは Road, Railway, Track, Square (いずれもLOD2-4) の子として使われる
TRAFFIC_AREA = FeatureProcessingDefinition(
    id="TrafficArea",
    target_elements=["tran:TrafficArea", "tran:AuxiliaryTrafficArea"],
    property_groups=[
        PropertyGroup(
            base_element=None,
            properties=[
                Property(
                    name="function",
                    path="./tran:function",
                    datatype="[]string",
                    predefined_codelist="TrafficArea_function",
                ),
                Property(
                    name="surfaceMaterial",
                    path="./tran:surfaceMaterial",
                    datatype="string",
                    predefined_codelist="TrafficArea_surfaceMaterial",
                ),
            ],
        ),
        # uro:TrafficAreaStructureAttribute (Road)
        PropertyGroup(
            base_element="./uro:trafficAreaStructureAttribute/uro:TrafficAreaStructureAttribute",
            properties=[
                Property(
                    name="numberOfLanes",
                    path="./uro:numberOfLanes",
                    datatype="integer",
                ),
            ],
        ),
        # uro:RailwayTrackAttribute (Railway)
        PropertyGroup(
            base_element="./uro:railwayTrackAttribute/uro:RailwayTrackAttribute",
            properties=[
                Property(
                    name="routeName",
                    path="./uro:routeName",
                    datatype="string",
                ),
                Property(
                    name="directionType",
                    path="./uro:directionType",
                    datatype="string",
                    predefined_codelist="RailwayTrackAttribute_directionType",
                ),
                Property(
                    name="trackType",
                    path="./uro:trackType",
                    datatype="string",
                    predefined_codelist="RailwayTrackAttribute_trackType",
                ),
                Property(
                    name="startPost",
                    path="./uro:startPost",
                    datatype="string",
                ),
                Property(
                    name="endPost",
                    path="./uro:endPost",
                    datatype="string",
                ),
                Property(
                    name="alignmentType",
                    path="./uro:alignmentType",
                    datatype="string",
                    predefined_codelist="RailwayTrackAttribute_alignmentType",
                ),
            ],
        ),
    ],
    lod_detection=LODDetection(
        lod2=["./tran:lod2MultiSurface"],
        lod3=["./tran:lod3MultiSurface"],
        lod4=["./tran:lod4MultiSurface"],
    ),
    emissions=FeatureEmissions(
        lod2=FeatureEmission(collect_all=["./tran:lod2MultiSurface//gml:Polygon"]),
        lod3=FeatureEmission(collect_all=["./tran:lod3MultiSurface//gml:Polygon"]),
        lod4=FeatureEmission(collect_all=["./tran:lod4MultiSurface//gml:Polygon"]),
    ),
)
