"""トンネルモデル (./tun/)"""

from .base import (
    FeatureEmission,
    FeatureEmissions,
    FeatureProcessingDefinition,
    LODDetection,
    Property,
    PropertyGroup,
)
from .common import facility_id_attribute_attrs

TUNNEL = FeatureProcessingDefinition(
    id="Tunnel",
    target_elements=["tun:Tunnel"],
    lod_detection=LODDetection(
        lod1=["./tun:lod1Solid"],
        lod2=["./tun:lod2Solid"],
        lod3=["./tun:lod3Solid"],
        lod4=["./tun:lod4Solid", "./tun:lod4MultiSurface"],
    ),
    property_groups=[
        PropertyGroup(
            base_element=None,
            properties=[
                Property(
                    name="class",
                    path="./tun:class",
                    datatype="string",
                    predefined_codelist="Tunnel_class",
                ),
                Property(
                    name="function",
                    path="./tun:function",
                    datatype="[]string",
                    predefined_codelist="Tunnel_function",
                ),
                Property(
                    name="yearOfConstruction",
                    path="./tun:yearOfConstruction",
                    datatype="integer",
                ),
                Property(
                    name="yearOfDemolition",
                    path="./tun:yearOfDemolition",
                    datatype="integer",
                ),
            ],
        ),
        PropertyGroup(
            base_element="./uro:tunBaseAttribute/uro:ConstructionBaseAttribute",
            properties=[
                Property(
                    name="adminOffice",
                    path="./uro:adminOffice",
                    datatype="string",
                ),
                Property(
                    name="adminType",
                    path="./uro:adminType",
                    datatype="string",
                    predefined_codelist="ConstructionBaseAttribute_adminType",
                ),
                Property(
                    name="administorator",
                    path="./uro:administorator",
                    datatype="string",
                ),
                Property(
                    name="completionYear",
                    path="./uro:completionYear",
                    datatype="integer",
                ),
                Property(
                    name="constructionStartYear",
                    path="./uro:constructionStartYear",
                    datatype="integer",
                ),
                Property(
                    name="facilityAge",
                    path="./uro:facilityAge",
                    datatype="integer",
                ),
                Property(
                    name="installer",
                    path="./uro:installer",
                    datatype="string",
                ),
                Property(
                    name="installerType",
                    path="./uro:installerType",
                    datatype="string",
                    predefined_codelist="ConstructionBaseAttribute_installerType",
                ),
                Property(
                    name="kana",
                    path="./uro:kana",
                    datatype="string",
                ),
                Property(
                    name="operatorType",
                    path="./uro:operatorType",
                    datatype="string",
                    predefined_codelist=None,
                ),
                Property(
                    name="purpose",
                    path="./uro:purpose",
                    datatype="string",
                    predefined_codelist="ConstructionBaseAttribute_purpose",
                ),
                Property(
                    name="specification",
                    path="./uro:specification",
                    datatype="string",
                ),
                Property(
                    name="structureOrdinance",
                    path="./uro:structureOrdinance",
                    datatype="string",
                ),
                Property(
                    name="update",
                    path="./uro:update",
                    datatype="date",
                ),
            ],
        ),
        PropertyGroup(
            base_element="./uro:tunStructureAttribute/uro:TunnelStructureAttribute",
            properties=[
                Property(
                    name="area",
                    path="./uro:area",
                    datatype="double",
                ),
                Property(
                    name="effectiveHeight",
                    path="./uro:effectiveHeight",
                    datatype="double",
                ),
                Property(
                    name="innerHeight",
                    path="./uro:innerHeight",
                    datatype="double",
                ),
                Property(
                    name="length",
                    path="./uro:length",
                    datatype="double",
                ),
                Property(
                    name="mouthType",
                    path="./uro:mouthType",
                    datatype="string",
                    predefined_codelist="TunnelStructureAttribute_mouthType",
                ),
                Property(
                    name="slopeType",
                    path="./uro:slopeType",
                    datatype="string",
                    predefined_codelist="ConstructionStructureAttribute_slopeType",
                ),
                Property(
                    name="tunnelSubtype",
                    path="./uro:tunnelSubtype",
                    datatype="string",
                    predefined_codelist="TunnelStructureAttribute_tunnelSubType",
                ),
                Property(
                    name="tunnelType",
                    path="./uro:tunnelType",
                    datatype="string",
                    predefined_codelist="TunnelStructureAttribute_tunnelType",
                ),
                Property(
                    name="width",
                    path="./uro:width",
                    datatype="double",
                ),
            ],
        ),
        PropertyGroup(
            base_element="./uro:tunFunctionalAttribute/uro:TunnelFunctionalAttribute",
            properties=[
                Property(
                    name="directionType",
                    path="./uro:directionType",
                    datatype="string",
                    predefined_codelist="ConstructionFunctionalAttribute_directionType",
                ),
                Property(
                    name="userType",
                    path="./uro:userType",
                    datatype="string",
                    predefined_codelist="TunnelFunctionalAttribute_userType",
                ),
            ],
        ),
        PropertyGroup(
            base_element="./uro:tunRiskAssessmentAttribute/uro:ConstructionRiskAssessmentAttribute",
            properties=[
                Property(
                    name="referenceDate",
                    path="./uro:referenceDate",
                    datatype="date",
                ),
                Property(
                    name="riskType",
                    path="./uro:riskType",
                    datatype="[]string",
                    predefined_codelist="ConstructionRiskAssessmentAttribute_riskType",
                ),
                Property(
                    name="status",
                    path="./uro:status",
                    datatype="[]string",
                    predefined_codelist="ConstructionRiskAssessmentAttribute_status",
                ),
                Property(
                    name="surveyYear",
                    path="./uro:surveyYear",
                    datatype="integer",
                ),
            ],
        ),
        PropertyGroup(
            base_element="./uro:tunDataQualityAttribute/uro:ConstructionDataQualityAttribute",
            properties=[
                Property(
                    name="appearanceSrcDesc",
                    path="./uro:appearanceSrcDesc",
                    datatype="[]string",
                    predefined_codelist="DataQualityAttribute_appearanceSrcDesc",
                ),
                Property(
                    name="dataAcquisition",
                    path="./uro:dataAcquisition",
                    datatype="string",
                ),
                Property(
                    name="geometrySrcDesc",
                    path="./uro:geometrySrcDesc",
                    datatype="[]string",
                    predefined_codelist="DataQualityAttribute_geometrySrcDesc",
                ),
                Property(
                    name="lod1HeightType",
                    path="./uro:lod1HeightType",
                    datatype="string",
                    predefined_codelist="DataQualityAttribute_lod1HeightType",
                ),
                Property(
                    name="lodType",
                    path="./uro:lodType",
                    datatype="[]string",
                ),
                Property(
                    name="photoScale",
                    path="./uro:photoScale",
                    datatype="integer",
                ),
                Property(
                    name="srcScale",
                    path="./uro:srcScale",
                    datatype="string",
                    predefined_codelist="DataQualityAttribute_srcScale",
                ),
                Property(
                    name="thematicSrcDesc",
                    path="./uro:thematicSrcDesc",
                    datatype="[]string",
                    predefined_codelist="DataQualityAttribute_thematicSrcDesc",
                ),
            ],
        ),
        PropertyGroup(
            base_element="./uro:tunFacilityIdAttribute/uro:FacilityIdAttribute",
            properties=facility_id_attribute_attrs,
        ),
        # TODO: uro:tunDisasterRiskAttribute (入れ子, polymorpohic)
        # TODO: uro:tunFacilityTypeAttribute
        # TODO: uro:tunFacilityAttribute
        # TODO: uro:tunDmAttribute
    ],
    emissions=FeatureEmissions(
        lod1=FeatureEmission(collect_all=[".//tun:lod1Solid//gml:Polygon"]),
        lod2=FeatureEmission(
            collect_all=[
                ".//tun:lod2MultiSurface//gml:Polygon",
                ".//tun:lod2Geometry//gml:Polygon",
            ],
            only_direct=["./tun:lod2Solid//gml:Polygon"],
        ),
        lod3=FeatureEmission(
            collect_all=[
                ".//tun:lod3MultiSurface//gml:Polygon",
                ".//tun:lod3Geometry//gml:Polygon",
                ".//tun:lod3Solid//gml:Polygon",
            ],
            only_direct=["./tun:lod3Solid//gml:Polygon"],
        ),
        lod4=FeatureEmission(
            collect_all=[
                ".//tun:lod4MultiSurface//gml:Polygon",
                ".//tun:lod4Geometry//gml:Polygon",
                ".//tun:lod4Solid//gml:Polygon",
            ],
            only_direct=[
                "./tun:lod4MultiSurface//gml:Polygon",
                "./tun:lod4Solid//gml:Polygon",
            ],
        ),
        semantic_parts=[
            ".//tun:GroundSurface",
            ".//tun:WallSurface",
            ".//tun:RoofSurface",
            ".//tun:OuterCeilingSurface",
            ".//tun:OuterFloorSurface",
            ".//tun:ClosureSurface",
            ".//tun:CeilingSurface",
            ".//tun:InteriorWallSurface",
            ".//tun:FloorSurface",
            ".//tun:TunnelInstallation",
            ".//tun:IntTunnelInstallation",
            ".//tun:TunnelFurniture",
            # TODO: 現状、tun:HollowSpace と tun:TunnelPart の概念は考慮していない
        ],
    ),
)

TUNNEL_BOUNDARY_SURFACE = FeatureProcessingDefinition(
    id="tun:_BoundarySurface",
    target_elements=[
        "tun:GroundSurface",
        "tun:WallSurface",
        "tun:RoofSurface",
        "tun:OuterCeilingSurface",
        "tun:OuterFloorSurface",
        "tun:ClosureSurface",
        "tun:CeilingSurface",
        "tun:InteriorWallSurface",
        "tun:FloorSurface",
    ],
    property_groups=[],
    lod_detection=LODDetection(
        lod2=["./tun:lod2MultiSurface"],
        lod3=["./tun:lod3MultiSurface"],
        lod4=["./tun:lod4MultiSurface"],
    ),
    emissions=FeatureEmissions(
        lod2=FeatureEmission(
            collect_all=[".//tun:lod2MultiSurface//gml:Polygon"],
            only_direct=["./tun:lod2MultiSurface//gml:Polygon"],
        ),
        lod3=FeatureEmission(
            collect_all=[".//tun:lod3MultiSurface//gml:Polygon"],
            only_direct=["./tun:lod3MultiSurface//gml:Polygon"],
        ),
        lod4=FeatureEmission(
            collect_all=[".//tun:lod4MultiSurface//gml:Polygon"],
            only_direct=["./tun:lod4MultiSurface//gml:Polygon"],
        ),
        semantic_parts=[
            "./tun:opening/tun:Door",
            "./tun:opening/tun:Window",
        ],
    ),
)

TUNNEL_OPENING = FeatureProcessingDefinition(
    id="tun:_Opening",
    target_elements=[
        "tun:Window",
        "tun:Door",
    ],
    property_groups=[],
    lod_detection=LODDetection(
        lod3=["./tun:lod3MultiSurface"],
        lod4=["./tun:lod4MultiSurface"],
    ),
    emissions=FeatureEmissions(
        lod3=FeatureEmission(collect_all=[".//tun:lod3MultiSurface//gml:Polygon"]),
        lod4=FeatureEmission(collect_all=[".//tun:lod4MultiSurface//gml:Polygon"]),
    ),
)

TUNNEL_INSTALLATION = FeatureProcessingDefinition(
    id="TunnelInstallation",
    target_elements=[
        "tun:TunnelInstallation",
    ],
    property_groups=[
        PropertyGroup(
            base_element=None,
            properties=[
                Property(
                    name="function",
                    path="./tun:function",
                    datatype="[]string",
                    predefined_codelist="TunnelInstallation_function",
                ),
            ],
        )
    ],
    lod_detection=LODDetection(
        lod2=["./tun:lod2Geometry"],
        lod3=["./tun:lod3Geometry"],
        lod4=["./tun:lod4Geometry"],
    ),
    emissions=FeatureEmissions(
        lod2=FeatureEmission(collect_all=[".//tun:lod2Geometry//gml:Polygon"]),
        lod3=FeatureEmission(collect_all=[".//tun:lod3Geometry//gml:Polygon"]),
        lod4=FeatureEmission(collect_all=[".//tun:lod4Geometry//gml:Polygon"]),
    ),
)

TUNNEL_INT_INSTALLATION = FeatureProcessingDefinition(
    id="IntTunnelInstallation",
    target_elements=[
        "tun:IntTunnelInstallation",
    ],
    property_groups=[
        PropertyGroup(
            base_element=None,
            properties=[
                Property(
                    name="function",
                    path="./tun:function",
                    datatype="[]string",
                    predefined_codelist="TunnelInstallation_function",
                ),
            ],
        ),
    ],
    lod_detection=LODDetection(
        lod3=["./tun:lod3Geometry"],
        lod4=["./tun:lod4Geometry"],
    ),
    emissions=FeatureEmissions(
        lod3=FeatureEmission(collect_all=[".//tun:lod3Geometry//gml:Polygon"]),
        lod4=FeatureEmission(collect_all=[".//tun:lod4Geometry//gml:Polygon"]),
    ),
)


TUNNEL_FURNITURE = FeatureProcessingDefinition(
    id="TunnelFurniture",
    target_elements=[
        "tun:TunnelFurniture",
    ],
    property_groups=[
        PropertyGroup(
            base_element=None,
            properties=[
                Property(
                    name="function",
                    path="./tun:function",
                    datatype="[]string",
                    predefined_codelist="TunnelFurniture_function",
                ),
            ],
        ),
    ],
    lod_detection=LODDetection(
        lod4=["./tun:lod4Geometry"],
    ),
    emissions=FeatureEmissions(
        lod4=FeatureEmission(collect_all=[".//tun:lod4Geometry//gml:Polygon"]),
    ),
)
