"""トンネルモデル (./tun/)"""

# FIXME:
# TODO: 以下、bldg:Building 用の定義をコピペしただけなので、内容は要検証

from .base import (
    FeatureEmission,
    FeatureEmissions,
    FeatureProcessingDefinition,
    LODDetection,
    Property,
    PropertyGroup,
)
from .common import facility_id_attribute_attrs

TUNNEL = FeatureProcessingDefinition(
    id="Tunnel",
    target_elements=["tun:Tunnel"],
    lod_detection=LODDetection(
        lod1=["./tun:lod1Solid"],
        lod2=["./tun:lod2Solid"],
        lod3=["./tun:lod3Solid"],
        lod4=["./tun:lod4Solid", "./tun:lod4MultiSurface"],
    ),
    property_groups=[
        PropertyGroup(
            base_element=None,
            properties=[
                Property(
                    name="usage",
                    path="./tun:usage",
                    datatype="[]string",
                    predefined_codelist="Tunnel_usage",
                ),
                Property(
                    name="yearOfConstruction",
                    path="./tun:yearOfConstruction",
                    datatype="integer",
                ),
                Property(
                    name="yearOfDemolition",
                    path="./tun:yearOfDemolition",
                    datatype="integer",
                ),
                Property(
                    name="roofType",
                    path="./tun:roofType",
                    datatype="string",
                    predefined_codelist="Tunnel_roofType",
                ),
                Property(
                    name="measuredHeight",
                    path="./tun:measuredHeight",
                    datatype="double",
                ),
                Property(
                    name="storeysAboveGround",
                    path="./tun:storeysAboveGround",
                    datatype="integer",
                ),
                Property(
                    name="storeysBelowGround",
                    path="./tun:storeysBelowGround",
                    datatype="integer",
                ),
                # Property(
                #     name="address",
                #     path="./tun:address",
                #     datatype="string",  # TODO: xAL をどう読むか
                # ),
            ],
        ),
        PropertyGroup(
            base_element="./uro:tunnelIDAttribute/uro:TunnelIDAttribute",
            properties=[
                Property(
                    name="tunnelID",
                    path="./uro:tunnelID",
                    datatype="string",
                ),
                Property(
                    name="branchID",
                    path="./uro:branchID",
                    datatype="integer",
                ),
                Property(
                    name="partID",
                    path="./uro:partID",
                    datatype="integer",
                ),
                Property(
                    name="prefecture",
                    path="./uro:prefecture",
                    datatype="string",
                    predefined_codelist="Common_prefecture",
                ),
                Property(
                    name="city",
                    path="./uro:city",
                    datatype="string",
                    predefined_codelist="Common_localPublicAuthorities",
                ),
            ],
        ),
        PropertyGroup(
            base_element="./uro:tunnelDetailAttribute/uro:TunnelDetailAttribute",
            properties=[
                Property(
                    name="serialNumberOfTunnelCertification",
                    path="./uro:serialNumberOfTunnelCertification",
                    datatype="string",
                ),
                Property(
                    name="siteArea",
                    path="./uro:siteArea",
                    datatype="double",
                ),
                Property(
                    name="totalFloorArea",
                    path="./uro:totalFloorArea",
                    datatype="double",
                ),
                Property(
                    name="tunnelFootprintArea",
                    path="./uro:tunnelFootprintArea",
                    datatype="double",
                ),
                Property(
                    name="tunnelRoofEdgeArea",
                    path="./uro:tunnelRoofEdgeArea",
                    datatype="double",
                ),
                Property(
                    name="developmentArea",
                    path="./uro:developmentArea",
                    datatype="double",
                ),
                Property(
                    name="tunnelStructureType",
                    path="./uro:tunnelStructureType",
                    datatype="string",
                    predefined_codelist="TunnelDetailAttribute_tunnelStructureType",
                ),
                Property(
                    name="tunnelStructureOrgType",
                    path="./uro:tunnelStructureOrgType",
                    datatype="string",
                ),
                Property(
                    name="fireproofStructureType",
                    path="./uro:fireproofStructureType",
                    datatype="string",
                    predefined_codelist="TunnelDetailAttribute_fireproofStructureType",
                ),
                Property(
                    name="urbanPlanType",
                    path="./uro:urbanPlanType",
                    datatype="string",
                    predefined_codelist="TunnelDetailAttribute_urbanPlanType",
                ),
                Property(
                    name="areaClassificationType",
                    path="./uro:areaClassificationType",
                    datatype="string",
                    predefined_codelist="Common_areaClassificationType",
                ),
                Property(
                    name="districtsAndZonesType",
                    path="./uro:districtsAndZonesType",
                    datatype="[]string",
                    predefined_codelist="Common_districtsAndZonesType",
                ),
                Property(
                    name="landUseType",
                    path="./uro:landUseType",
                    datatype="string",
                    predefined_codelist="Common_landUseType",
                ),
                Property(
                    name="reference",
                    path="./uro:reference",
                    datatype="string",
                ),
                Property(
                    name="majorUsage",
                    path="./uro:majorUsage",
                    datatype="string",
                ),
                Property(
                    name="majorUsage2",
                    path="./uro:majorUsage2",
                    datatype="string",
                ),
                Property(
                    name="orgUsage",
                    path="./uro:orgUsage",
                    datatype="string",
                ),
                Property(
                    name="orgUsage2",
                    path="./uro:orgUsage2",
                    datatype="string",
                ),
                Property(
                    name="detailedUsage",
                    path="./uro:detailedUsage",
                    datatype="string",
                ),
                Property(
                    name="detailedUsage2",
                    path="./uro:detailedUsage2",
                    datatype="string",
                ),
                Property(
                    name="detailedUsage3",
                    path="./uro:detailedUsage3",
                    datatype="string",
                ),
                Property(
                    name="groundFloorUsage",
                    path="./uro:groundFloorUsage",
                    datatype="string",
                ),
                Property(
                    name="secondFloorUsage",
                    path="./uro:secondFloorUsage",
                    datatype="string",
                ),
                Property(
                    name="thirdFloorUsage",
                    path="./uro:thirdFloorUsage",
                    datatype="string",
                ),
                Property(
                    name="basementUsage",
                    path="./uro:basementUsage",
                    datatype="string",
                ),
                Property(
                    name="basementFirstUsage",
                    path="./uro:basementFirstUsage",
                    datatype="string",
                ),
                Property(
                    name="basementSecondUsage",
                    path="./uro:basementSecondUsage",
                    datatype="string",
                ),
                Property(
                    name="vacancy",
                    path="./uro:vacancy",
                    datatype="string",
                    predefined_codelist="TunnelDetailAttribute_vacancy",
                ),
                Property(
                    name="tunnelCoverageRate",
                    path="./uro:tunnelCoverageRate",
                    datatype="double",
                ),
                Property(
                    name="floorAreaRate",
                    path="./uro:floorAreaRate",
                    datatype="double",
                ),
                Property(
                    name="specifiedTunnelCoverageRate",
                    path="./uro:specifiedTunnelCoverageRate",
                    datatype="double",
                ),
                Property(
                    name="specifiedFloorAreaRate",
                    path="./uro:specifiedFloorAreaRate",
                    datatype="double",
                ),
                Property(
                    name="standardFloorAreaRate",
                    path="./uro:standardFloorAreaRate",
                    datatype="double",
                ),
                Property(
                    name="tunnelHeight",
                    path="./uro:buidingHeight",
                    datatype="double",
                ),
                Property(
                    name="eaveHeight",
                    path="./uro:eaveHeight",
                    datatype="double",
                ),
                Property(
                    name="surveyYear",
                    path="./uro:surveyYear",
                    datatype="integer",
                ),
            ],
        ),
        PropertyGroup(
            base_element="./uro:largeCustomerFacilityAttribute/uro:LargeCustomerFacilityAttribute",
            properties=[
                Property(
                    name="class",
                    path="./uro:class",
                    datatype="string",
                    predefined_codelist="LargeCustomerFacilityAttribute_class",
                ),
                Property(
                    name="name",
                    path="./uro:name",
                    datatype="string",
                ),
                Property(
                    name="capacity",
                    path="./uro:capacity",
                    datatype="integer",
                ),
                Property(
                    name="owner",
                    path="./uro:owner",
                    datatype="string",
                ),
                Property(
                    name="totalFloorArea",
                    path="./uro:totalFloorArea",
                    datatype="double",
                ),
                Property(
                    name="totalStoreFloorArea",
                    path="./uro:totalStoreFloorArea",
                    datatype="double",
                ),
                Property(
                    name="inauguralDate",
                    path="./uro:inauguralDate",
                    datatype="date",
                ),
                Property(
                    name="yearOpened",
                    path="./uro:yearOpened",
                    datatype="integer",
                ),
                Property(
                    name="yearClosed",
                    path="./uro:yearClosed",
                    datatype="integer",
                ),
                Property(
                    name="keyTenants",
                    path="./uro:keyTenants",
                    datatype="string",
                ),
                Property(
                    name="availability",
                    path="./uro:availability",
                    datatype="boolean",
                ),
                Property(
                    name="urbanPlanType",
                    path="./uro:urbanPlanType",
                    datatype="string",
                    predefined_codelist="Common_urbanPlanType",
                ),
                Property(
                    name="areaClassificationType",
                    path="./uro:areaClassificationType",
                    datatype="string",
                    predefined_codelist="Common_areaClassificationType",
                ),
                Property(
                    name="districtsAndZonesType",
                    path="./uro:districtsAndZonesType",
                    datatype="[]string",
                    predefined_codelist="Common_districtsAndZonesType",
                ),
                Property(
                    name="landUseType",
                    path="./uro:landUseType",
                    datatype="string",
                    predefined_codelist="Common_landUseType",
                ),
                Property(
                    name="reference",
                    path="./uro:reference",
                    datatype="string",
                ),
                Property(
                    name="note",
                    path="./uro:note",
                    datatype="string",
                ),
                Property(
                    name="surveyYear",
                    path="./uro:surveyYear",
                    datatype="integer",
                ),
            ],
        ),
        PropertyGroup(
            base_element="./uro:tunnelDataQualityAttribute/uro:TunnelDataQualityAttribute",
            properties=[
                Property(
                    name="srcScale",
                    path="./uro:srcScale",
                    datatype="[]string",
                    predefined_codelist="TunnelDataQualityAttribute_srcScale",
                ),
                Property(
                    name="geometrySrcDesc",
                    path="./uro:geometrySrcDesc",
                    datatype="[]string",
                    predefined_codelist="TunnelDataQualityAttribute_geometrySrcDesc",
                ),
                Property(
                    name="thematicSrcDesc",
                    path="./uro:thematicSrcDesc",
                    datatype="[]string",
                    predefined_codelist="TunnelDataQualityAttribute_thematicSrcDesc",
                ),
                Property(
                    name="appearanceSrcDesc",
                    path="./uro:appearanceSrcDesc",
                    datatype="[]string",
                    predefined_codelist="TunnelDataQualityAttribute_appearanceSrcDesc",
                ),
                Property(
                    name="lod1HeightType",
                    path="./uro:lod1HeightType",
                    datatype="string",
                    predefined_codelist="TunnelDataQualityAttribute_lod1HeightType",
                ),
                Property(
                    name="lodType",
                    path="./uro:lodType",
                    datatype="[]string",
                ),
            ],
        ),
        PropertyGroup(
            base_element="./uro:tunFacilityIdAttribute/uro:FacilityIdAttribute",
            properties=facility_id_attribute_attrs,
        ),
        # TODO: uro:tunnelDisasterRiskAttribute (入れ子, polymorpohic)
        # TODO: uro:keyValuePairAttribute
        # (TODO: uro:ifcTunnelAttribute)
        # TODO: uro:indoorTunnelAttribute
        # TODO: uro:tunFacilityTypeAttribute
        # TODO: uro:tunFacilityAttribute
        # TODO: uro:tunDmAttribute
    ],
    emissions=FeatureEmissions(
        lod1=FeatureEmission(collect_all=[".//tun:lod1Solid//gml:Polygon"]),
        lod2=FeatureEmission(
            collect_all=[
                ".//tun:lod2MultiSurface//gml:Polygon",
                ".//tun:lod2Geometry//gml:Polygon",
            ],
            only_direct=["./tun:lod2Solid//gml:Polygon"],
        ),
        lod3=FeatureEmission(
            collect_all=[
                ".//tun:lod3MultiSurface//gml:Polygon",
                ".//tun:lod3Geometry//gml:Polygon",
                ".//tun:lod3Solid//gml:Polygon",
            ],
            only_direct=["./tun:lod3Solid//gml:Polygon"],
        ),
        lod4=FeatureEmission(
            collect_all=[
                ".//tun:lod4MultiSurface//gml:Polygon",
                ".//tun:lod4Geometry//gml:Polygon",
                ".//tun:lod4Solid//gml:Polygon",
            ],
            only_direct=[
                "./tun:lod4MultiSurface//gml:Polygon",
                "./tun:lod4Solid//gml:Polygon",
            ],
        ),
        semantic_parts=[
            ".//tun:GroundSurface",
            ".//tun:WallSurface",
            ".//tun:RoofSurface",
            ".//tun:OuterCeilingSurface",
            ".//tun:OuterFloorSurface",
            ".//tun:ClosureSurface",
            ".//tun:CeilingSurface",
            ".//tun:InteriorWallSurface",
            ".//tun:FloorSurface",
            ".//tun:TunnelInstallation",
            ".//tun:IntTunnelInstallation",
            ".//tun:TunnelFurniture",
            # TODO: 現状、tun:HollowSpace と tun:TunnelPart の概念は考慮していない
        ],
    ),
)

TUNNEL_BOUNDARY_SURFACE = FeatureProcessingDefinition(
    id="tun:_BoundarySurface",
    target_elements=[
        "tun:GroundSurface",
        "tun:WallSurface",
        "tun:RoofSurface",
        "tun:OuterCeilingSurface",
        "tun:OuterFloorSurface",
        "tun:ClosureSurface",
        "tun:CeilingSurface",
        "tun:InteriorWallSurface",
        "tun:FloorSurface",
    ],
    property_groups=[],
    lod_detection=LODDetection(
        lod2=["./tun:lod2MultiSurface"],
        lod3=["./tun:lod3MultiSurface"],
        lod4=["./tun:lod4MultiSurface"],
    ),
    emissions=FeatureEmissions(
        lod2=FeatureEmission(
            collect_all=[".//tun:lod2MultiSurface//gml:Polygon"],
            only_direct=["./tun:lod2MultiSurface//gml:Polygon"],
        ),
        lod3=FeatureEmission(
            collect_all=[".//tun:lod3MultiSurface//gml:Polygon"],
            only_direct=["./tun:lod3MultiSurface//gml:Polygon"],
        ),
        lod4=FeatureEmission(
            collect_all=[".//tun:lod4MultiSurface//gml:Polygon"],
            only_direct=["./tun:lod4MultiSurface//gml:Polygon"],
        ),
        semantic_parts=[
            "./tun:opening/tun:Door",
            "./tun:opening/tun:Window",
        ],
    ),
)

TUNNEL_OPENING = FeatureProcessingDefinition(
    id="tun:_Opening",
    target_elements=[
        "tun:Window",
        "tun:Door",
    ],
    property_groups=[
        # TODO: uro:indoorOpeningAttribute
    ],
    lod_detection=LODDetection(
        lod3=["./tun:lod3MultiSurface"],
        lod4=["./tun:lod4MultiSurface"],
    ),
    emissions=FeatureEmissions(
        lod3=FeatureEmission(collect_all=[".//tun:lod3MultiSurface//gml:Polygon"]),
        lod4=FeatureEmission(collect_all=[".//tun:lod4MultiSurface//gml:Polygon"]),
    ),
)

TUNNEL_INSTALLATION = FeatureProcessingDefinition(
    id="TunnelInstallation",
    target_elements=[
        "tun:TunnelInstallation",
    ],
    property_groups=[
        PropertyGroup(
            base_element=None,
            properties=[
                Property(
                    name="function",
                    path="./tun:function",
                    datatype="[]string",
                    predefined_codelist="TunnelInstallation_function",
                ),
            ],
        )
    ],
    lod_detection=LODDetection(
        lod2=["./tun:lod2Geometry"],
        lod3=["./tun:lod3Geometry"],
        lod4=["./tun:lod4Geometry"],
    ),
    emissions=FeatureEmissions(
        lod2=FeatureEmission(collect_all=[".//tun:lod2Geometry//gml:Polygon"]),
        lod3=FeatureEmission(collect_all=[".//tun:lod3Geometry//gml:Polygon"]),
        lod4=FeatureEmission(collect_all=[".//tun:lod4Geometry//gml:Polygon"]),
    ),
)

TUNNEL_INT_INSTALLATION = FeatureProcessingDefinition(
    id="IntTunnelInstallation",
    target_elements=[
        "tun:IntTunnelInstallation",
    ],
    property_groups=[
        PropertyGroup(
            base_element=None,
            properties=[
                Property(
                    name="function",
                    path="./tun:function",
                    datatype="[]string",
                    predefined_codelist="TunnelInstallation_function",
                ),
            ],
        ),
        # TODO: uro:indoorInstallationAttribute
    ],
    lod_detection=LODDetection(
        lod2=["./tun:lod2Geometry"],
        lod3=["./tun:lod3Geometry"],
        lod4=["./tun:lod4Geometry"],
    ),
    emissions=FeatureEmissions(
        lod2=FeatureEmission(collect_all=[".//tun:lod2Geometry//gml:Polygon"]),
        lod3=FeatureEmission(collect_all=[".//tun:lod3Geometry//gml:Polygon"]),
        lod4=FeatureEmission(collect_all=[".//tun:lod4Geometry//gml:Polygon"]),
    ),
)


TUNNEL_FURNITURE = FeatureProcessingDefinition(
    id="TunnelFurniture",
    target_elements=[
        "tun:TunnelFurniture",
    ],
    property_groups=[
        PropertyGroup(
            base_element=None,
            properties=[
                Property(
                    name="class",
                    path="./tun:class",
                    datatype="string",
                    predefined_codelist="TunnelFurniture_class",
                ),
                Property(
                    name="function",
                    path="./tun:function",
                    datatype="[]string",
                    predefined_codelist="TunnelFurniture_function",
                ),
            ],
        ),
        # TODO: uro:indoorFurnitureAttribute
    ],
    lod_detection=LODDetection(
        lod4=["./tun:lod4Geometry"],
    ),
    emissions=FeatureEmissions(
        lod4=FeatureEmission(collect_all=[".//tun:lod4Geometry//gml:Polygon"]),
    ),
)
