"""区域モデル (./area/)、都市計画決定情報モデル (./urf/)"""

from .base import (
    Attribute,
    AttributeGroup,
    FeatureEmission,
    FeatureEmissions,
    FeatureProcessingDefinition,
    LODDetection,
)

# urf:Zone の属性
_base_attributes = [
    # attributes inherited from urf:Zone
    AttributeGroup(
        base_element=None,
        attributes=[
            Attribute(
                name="function",
                path="./urf:function",
                datatype="[]string",
            ),
            Attribute(
                name="usage",
                path="./urf:usage",
                datatype="[]string",
            ),
            Attribute(
                name="areaClassificationType",
                path="./urf:areaClassificationType",
                datatype="string",
                predefined_codelist="Common_areaClassificationType",
            ),
            Attribute(
                name="city",
                path="./urf:city",
                datatype="string",
                predefined_codelist="Common_localPublicAuthorities",
            ),
            Attribute(
                name="custodian",
                path="./urf:custodian",
                datatype="string",
            ),
            Attribute(
                name="enactmentFiscalYear",
                path="./urf:enactmentFiscalYear",
                datatype="integer",
            ),
            Attribute(
                name="expirationFiscalYear",
                path="./urf:expirationFiscalYear",
                datatype="integer",
            ),
            Attribute(
                name="legalGrounds",
                path="./urf:legalGrounds",
                datatype="string",
            ),
            Attribute(
                name="location",
                path="./urf:location",
                datatype="string",
            ),
            Attribute(
                name="nominalArea",
                path="./urf:nominalArea",
                datatype="double",
            ),
            Attribute(
                name="note",
                path="./urf:note",
                datatype="string",
            ),
            Attribute(
                name="notificationNumber",
                path="./urf:notificationNumber",
                datatype="string",
            ),
            Attribute(
                name="prefecture",
                path="./urf:prefecture",
                datatype="string",
                predefined_codelist="Common_prefecture",
            ),
            Attribute(
                name="reason",
                path="./urf:reason",
                datatype="string",
            ),
            Attribute(
                name="reference",
                path="./urf:reference",
                datatype="string",
            ),
            Attribute(
                name="urbanPlanType",
                path="./urf:urbanPlanType",
                datatype="string",
                predefined_codelist="Common_urbanPlanType",
            ),
            Attribute(
                name="validFrom",
                path="./urf:validFrom",
                datatype="date",
            ),
            Attribute(
                name="validFromType",
                path="./urf:validFromType",
                datatype="string",
                predefined_codelist="Common_validType",
            ),
            Attribute(
                name="validTo",
                path="./urf:validTo",
                datatype="date",
            ),
            Attribute(
                name="validToType",
                path="./urf:validToType",
                datatype="string",
                predefined_codelist="Common_validType",
            ),
        ],
    ),
]

URF_URBAN_PLANNING_AREA = FeatureProcessingDefinition(
    id="urf:UrbanPlanningArea",
    target_elements=["urf:UrbanPlanningArea"],
    attribute_groups=[
        *_base_attributes,
        AttributeGroup(
            base_element=None,
            attributes=[
                Attribute(
                    name="function",
                    path="./urf:function",
                    datatype="[]string",
                    predefined_codelist="Common_urbanPlanType",
                ),
                Attribute(
                    name="areaClassification",
                    path="./urf:areaClassification",
                    datatype="string",
                    predefined_codelist="Common_availabilityType",
                ),
                Attribute(
                    name="cityArea",
                    path="./urf:cityArea",
                    datatype="double",
                ),
                Attribute(
                    name="cityPopulation",
                    path="./urf:cityPopulation",
                    datatype="integer",
                ),
                Attribute(
                    name="policyForAreaClassification",
                    path="./urf:policyForAreaClassification",
                    datatype="string",
                ),
                Attribute(
                    name="policyForUrbanPlanDecision",
                    path="./urf:policyForUrbanPlanDecision",
                    datatype="string",
                ),
                Attribute(
                    name="population",
                    path="./urf:population",
                    datatype="integer",
                ),
                Attribute(
                    name="purposeForUrbanPlan",
                    path="./urf:purposeForUrbanPlan",
                    datatype="string",
                ),
                Attribute(
                    name="reasonForAreaClassification",
                    path="./urf:reasonForAreaClassification",
                    datatype="string",
                ),
            ],
        ),
    ],
    lod_detection=LODDetection(
        lod0=["./urf:lod0MultiSurface"],
        lod1=["./urf:lod1MultiSurface"],
    ),
    emissions=FeatureEmissions(
        lod0=FeatureEmission(collect_all=["./urf:lod0MultiSurface//gml:Polygon"]),
        lod1=FeatureEmission(collect_all=["./urf:lod1MultiSurface//gml:Polygon"]),
    ),
)

URF_QUASI_URBAN_PLANNING_AREA = FeatureProcessingDefinition(
    id="urf:QuasiUrbanPlanningArea",
    target_elements=["urf:QuasiUrbanPlanningArea"],
    attribute_groups=[
        *_base_attributes,
        AttributeGroup(
            base_element=None,
            attributes=[
                Attribute(
                    name="function",
                    path="./urf:function",
                    datatype="[]string",
                    predefined_codelist="Common_urbanPlanType",
                ),
                Attribute(
                    name="cityArea",
                    path="./urf:cityArea",
                    datatype="double",
                ),
                Attribute(
                    name="cityPopulation",
                    path="./urf:cityPopulation",
                    datatype="integer",
                ),
                Attribute(
                    name="population",
                    path="./urf:population",
                    datatype="integer",
                ),
            ],
        ),
    ],
    lod_detection=LODDetection(
        lod0=["./urf:lod0MultiSurface"],
        lod1=["./urf:lod1MultiSurface"],
    ),
    emissions=FeatureEmissions(
        lod0=FeatureEmission(collect_all=["./urf:lod0MultiSurface//gml:Polygon"]),
        lod1=FeatureEmission(collect_all=["./urf:lod1MultiSurface//gml:Polygon"]),
    ),
)

URF_AREA_CLASSIFICATION = FeatureProcessingDefinition(
    id="urf:AreaClassification",
    target_elements=["urf:AreaClassification"],
    attribute_groups=[
        *_base_attributes,
        AttributeGroup(
            base_element=None,
            attributes=[
                Attribute(
                    name="function",
                    path="./urf:function",
                    datatype="[]string",
                    predefined_codelist="Common_areaClassificationType",
                ),
                Attribute(
                    name="population",
                    path="./urf:population",
                    datatype="integer",
                ),
            ],
        ),
    ],
    lod_detection=LODDetection(
        lod0=["./urf:lod0MultiSurface"],
        lod1=["./urf:lod1MultiSurface"],
    ),
    emissions=FeatureEmissions(
        lod0=FeatureEmission(collect_all=["./urf:lod0MultiSurface//gml:Polygon"]),
        lod1=FeatureEmission(collect_all=["./urf:lod1MultiSurface//gml:Polygon"]),
    ),
)

URF_DISTRICTS_AND_ZONES = FeatureProcessingDefinition(
    id="urf:DistrictsAndZones",
    target_elements=[
        "urf:AircraftNoiseControlZone",
        "urf:ConservationZoneForClustersOfTraditionalStructures",
        "urf:DistributionBusinessZone",
        "urf:DistrictsAndZones",
        "urf:ExceptionalFloorAreaRateDistrict",
        "urf:FirePreventionDistrict",
        "urf:GreenSpaceConservationDistrict",
        "urf:HeightControlDistrict",
        "urf:HighLevelUseDistrict",
        "urf:HighRiseResidentialAttractionDistrict",
        "urf:HousingControlArea",
        "urf:LandscapeZone",
        "urf:ParkingPlaceDevelopmentZone",
        "urf:PortZone",
        "urf:ProductiveGreenZone",
        "urf:ResidentialEnvironmentImprovementDistrict",
        "urf:ScenicDistrict",
        "urf:SpecialGreenSpaceConservationDistrict",
        "urf:SpecialUrbanRenaissanceDistrict",
        "urf:SpecialUseAttractionDistrict",
        "urf:SpecialUseDistrict",
        "urf:SpecialUseRestrictionDistrict",
        "urf:SpecialZoneForPreservationOfHistoricalLandscape",
        "urf:SpecifiedBlock",
        "urf:SpecifiedDisasterPreventionBlockImprovementZone",
        "urf:TreePlantingDistrict",
        "urf:UseDistrict",
        "urf:ZoneForPreservationOfHistoricalLandscape",
    ],
    attribute_groups=[
        *_base_attributes,
        AttributeGroup(
            base_element=None,
            attributes=[
                Attribute(
                    name="function",
                    path="./urf:function",
                    datatype="[]string",
                    predefined_codelist="Common_districtsAndZonesType",
                ),
                Attribute(
                    name="areaInTotal",
                    path="./urf:areaInTotal",
                    datatype="double",
                ),
                Attribute(
                    name="buildingCoverageRate",
                    path="./urf:buildingCoverageRate",
                    datatype="double",
                ),
                Attribute(
                    name="buildingDesignRestriction",
                    path="./urf:buildingDesignRestriction",
                    datatype="string",
                ),
                Attribute(
                    name="buildingHeightLimits",
                    path="./urf:buildingHeightLimits",
                    datatype="double",
                ),
                Attribute(
                    name="buildingRestrictions",
                    path="./urf:buildingRestrictions",
                    datatype="string",
                ),
                Attribute(
                    name="floorAreaRate",
                    path="./urf:floorAreaRate",
                    datatype="double",
                ),
                Attribute(
                    name="guidelinePublicationDate",
                    path="./urf:guidelinePublicationDate",
                    datatype="date",
                ),
                Attribute(
                    name="maximumBuildingCoverageRate",
                    path="./urf:maximumBuildingCoverageRate",
                    datatype="double",
                ),
                Attribute(
                    name="maximumBuildingHeight",
                    path="./urf:maximumBuildingHeight",
                    datatype="string",
                ),
                Attribute(
                    name="maximumFloorAreaRate",
                    path="./urf:maximumFloorAreaRate",
                    datatype="double",
                ),
                Attribute(
                    name="minimumBuildingArea",
                    path="./urf:minimumBuildingArea",
                    datatype="double",
                ),
                Attribute(
                    name="minimumBuildingHeight",
                    path="./urf:minimumBuildingHeight",
                    datatype="double",
                ),
                Attribute(
                    name="minimumFloorAreaRate",
                    path="./urf:minimumFloorAreaRate",
                    datatype="double",
                ),
                Attribute(
                    name="minimumFrontageRate",
                    path="./urf:minimumFrontageRate",
                    datatype="double",
                ),
                Attribute(
                    name="minimumGreeningRate",
                    path="./urf:minimumGreeningRate",
                    datatype="double",
                ),
                Attribute(
                    name="minimumSiteArea",
                    path="./urf:minimumSiteArea",
                    datatype="double",
                ),
                Attribute(
                    name="otherRestrictions",
                    path="./urf:otherRestrictions",
                    datatype="string",
                ),
                Attribute(
                    name="requirement",
                    path="./urf:requirement",
                    datatype="string",
                    predefined_codelist="SpecialGreenSpaceConservationDistrict_requirement",
                ),
                Attribute(
                    name="setbackRestrictions",
                    path="./urf:setbackRestrictions",
                    datatype="string",
                ),
                Attribute(
                    name="setbackSize",
                    path="./urf:setbackSize",
                    datatype="string",
                ),
                Attribute(
                    name="shadeRegulation",
                    path="./urf:shadeRegulation",
                    datatype="string",
                ),
                Attribute(
                    name="specification",
                    path="./urf:specification",
                    datatype="string",
                    predefined_codelist="Common_availabilityType",
                ),
                Attribute(
                    name="useToBeInduced",
                    path="./urf:useToBeInduced",
                    datatype="string",
                ),
                Attribute(
                    name="urf:wallSetbackDistance",
                    path="./urf:wallSetbackDistance",
                    datatype="string",
                ),
                Attribute(
                    name="urf:wallSetbackDistanceWithAdjoiningLand",
                    path="./urf:wallSetbackDistanceWithAdjoiningLand",
                    datatype="double",
                ),
                Attribute(
                    name="urf:wallSetbackDistanceWithRoad",
                    path="./urf:wallSetbackDistanceWithRoad",
                    datatype="double",
                ),
                Attribute(
                    name="urf:zoneNumber",
                    path="./urf:zoneNumber",
                    datatype="string",
                ),
            ],
        ),
    ],
    lod_detection=LODDetection(
        lod0=["./urf:lod0MultiSurface"],
        lod1=["./urf:lod1MultiSurface"],
    ),
    emissions=FeatureEmissions(
        lod0=FeatureEmission(collect_all=["./urf:lod0MultiSurface//gml:Polygon"]),
        lod1=FeatureEmission(collect_all=["./urf:lod1MultiSurface//gml:Polygon"]),
    ),
)

URF_PROJECT_PROMOTION_AREA = FeatureProcessingDefinition(
    id="urf:ProjectPromotionArea",
    target_elements=[
        "urf:LandReadjustmentPromotionArea",
        "urf:LandReadjustmentPromotionAreasForCoreBusinessUrbanDevelopment",
        "urf:ProjectPromotionArea",
        "urf:ResidentialBlockConstructionPromotionArea",
        "urf:UrbanRedevelopmentPromotionArea",
    ],
    attribute_groups=[
        *_base_attributes,
        AttributeGroup(
            base_element=None,
            attributes=[
                Attribute(
                    name="function",
                    path="./urf:function",
                    datatype="[]string",
                    predefined_codelist="ProjectPromotionArea_function",
                ),
                Attribute(
                    name="developmentPolicy",
                    path="./urf:developmentPolicy",
                    datatype="string",
                ),
                Attribute(
                    name="publicFacilities",
                    path="./urf:publicFacilities",
                    datatype="string",
                ),
                Attribute(
                    name="publicFacilitiesPlans",
                    path="./urf:publicFacilitiesPlans",
                    datatype="string",
                ),
                Attribute(
                    name="unitArea",
                    path="./urf:unitArea",
                    datatype="string",
                ),
            ],
        ),
    ],
    lod_detection=LODDetection(
        lod0=["./urf:lod0MultiSurface"],
        lod1=["./urf:lod1MultiSurface"],
    ),
    emissions=FeatureEmissions(
        lod0=FeatureEmission(collect_all=["./urf:lod0MultiSurface//gml:Polygon"]),
        lod1=FeatureEmission(collect_all=["./urf:lod1MultiSurface//gml:Polygon"]),
    ),
)

URF_UNUSED_LAND_USE_PROMOTION_AREA = FeatureProcessingDefinition(
    id="urf:UnusedLandUsePromotionArea",
    target_elements=["urf:UnusedLandUsePromotionArea"],
    attribute_groups=_base_attributes,
    lod_detection=LODDetection(
        lod0=["./urf:lod0MultiSurface"],
        lod1=["./urf:lod1MultiSurface"],
    ),
    emissions=FeatureEmissions(
        lod0=FeatureEmission(collect_all=["./urf:lod0MultiSurface//gml:Polygon"]),
        lod1=FeatureEmission(collect_all=["./urf:lod1MultiSurface//gml:Polygon"]),
    ),
)

URF_URBAN_DISASTER_RECOVERY_PROMOTION_AREA = FeatureProcessingDefinition(
    id="urf:UrbanDisasterRecoveryPromotionArea",
    target_elements=["urf:UrbanDisasterRecoveryPromotionArea"],
    attribute_groups=[
        *_base_attributes,
        AttributeGroup(
            base_element=None,
            attributes=[
                Attribute(
                    name="emergencyRecoveryPolicy",
                    path="./urf:emergencyRecoveryPolicy",
                    datatype="string",
                ),
                Attribute(
                    name="expirationDate",
                    path="./urf:expirationDate",
                    datatype="date",
                ),
                Attribute(
                    name="plannedProjectType",
                    path="./urf:plannedProjectType",
                    datatype="string",
                    predefined_codelist="UrbanDevelopmentProject_function",
                ),
            ],
        ),
    ],
    lod_detection=LODDetection(
        lod0=["./urf:lod0MultiSurface"],
        lod1=["./urf:lod1MultiSurface"],
    ),
    emissions=FeatureEmissions(
        lod0=FeatureEmission(collect_all=["./urf:lod0MultiSurface//gml:Polygon"]),
        lod1=FeatureEmission(collect_all=["./urf:lod1MultiSurface//gml:Polygon"]),
    ),
)

URF_URBAN_FACILITY = FeatureProcessingDefinition(
    id="urf:UrbanFacility",
    target_elements=[
        "urf:CollectiveFacilitiesForReconstruction",
        "urf:CollectiveFacilitiesForReconstructionAndRevitalization",
        "urf:CollectiveFacilitiesForTsunamiDisasterPrevention",
        "urf:CollectiveGovernmentAndPublicOfficeFacilities",
        "urf:CollectiveHousingFacilities",
        "urf:CollectiveUrbanDisasterPreventionFacilities",
        "urf:DistributionBusinessPark",
        "urf:EducationalAndCulturalFacility",
        "urf:FireProtectionFacility",
        "urf:FloodPreventionFacility",
        "urf:MarketsSlaughterhousesCrematoria",
        "urf:MedicalFacility",
        "urf:OpenSpaceForPublicUse",
        "urf:SandControlFacility",
        "urf:SnowProtectionFacility",
        "urf:SocialWelfareFacility",
        "urf:SupplyFacility",
        "urf:TelecommunicationFacility",
        "urf:TideFacility",
        "urf:TrafficFacility",
        "urf:TreatmentFacility",
        "urf:UrbanFacility",
        "urf:UrbanFacilityStipulatedByCabinetOrder",
        "urf:Waterway",
        "urf:WindProtectionFacility",
    ],
    attribute_groups=[
        *_base_attributes,
        AttributeGroup(
            base_element=None,
            attributes=[
                Attribute(
                    name="function",
                    path="./urf:function",
                    datatype="[]string",
                    predefined_codelist="UrbanFacility_function",
                ),
                Attribute(
                    name="buildingCoverageRate",
                    path="./urf:buildingCoverageRate",
                    datatype="double",
                ),
                Attribute(
                    name="distributionBusinessPark",
                    path="./urf:distributionBusinessPark",
                    datatype="string",
                ),
                Attribute(
                    name="endLocation",
                    path="./urf:endLocation",
                    datatype="string",
                ),
                Attribute(
                    name="floorAreaRate",
                    path="./urf:floorAreaRate",
                    datatype="double",
                ),
                Attribute(
                    name="housingFacilities",
                    path="./urf:housingFacilities",
                    datatype="string",
                ),
                Attribute(
                    name="length",
                    path="./urf:length",
                    datatype="double",
                ),
                Attribute(
                    name="maximumBuildingCoverageRate",
                    path="./urf:maximumBuildingCoverageRate",
                    datatype="double",
                ),
                Attribute(
                    name="maximumBuildingHeight",
                    path="./urf:maximumBuildingHeight",
                    datatype="double",
                ),
                Attribute(
                    name="maximumFloorAreaRate",
                    path="./urf:maximumFloorAreaRate",
                    datatype="double",
                ),
                Attribute(
                    name="minimumBuildingHeight",
                    path="./urf:minimumBuildingHeight",
                    datatype="double",
                ),
                Attribute(
                    name="minimumFloorAreaRate",
                    path="./urf:minimumFloorAreaRate",
                    datatype="double",
                ),
                Attribute(
                    name="number",
                    path="./urf:number",
                    datatype="string",
                ),
                Attribute(
                    name="numberOfHighRiseHousing",
                    path="./urf:numberOfHighRiseHousing",
                    datatype="integer",
                ),
                Attribute(
                    name="numberOfLowRiseHousing",
                    path="./urf:numberOfLowRiseHousing",
                    datatype="integer",
                ),
                Attribute(
                    name="numberOfMiddleRiseHousing",
                    path="./urf:numberOfMiddleRiseHousing",
                    datatype="integer",
                ),
                Attribute(
                    name="publicAndUtilityFacilities",
                    path="./urf:publicAndUtilityFacilities",
                    datatype="string",
                ),
                Attribute(
                    name="publicFacilities",
                    path="./urf:publicFacilities",
                    datatype="string",
                ),
                Attribute(
                    name="publicFacilitiesAllocationPolicy",
                    path="./urf:publicFacilitiesAllocationPolicy",
                    datatype="string",
                ),
                Attribute(
                    name="scheduledExecutor",
                    path="./urf:scheduledExecutor",
                    datatype="string",
                ),
                Attribute(
                    name="setbackSize",
                    path="./urf:setbackSize",
                    datatype="string",
                ),
                Attribute(
                    name="specificUtilityAndPublicFacilities",
                    path="./urf:specificUtilityAndPublicFacilities",
                    datatype="string",
                ),
                Attribute(
                    name="startLocation",
                    path="./urf:startLocation",
                    datatype="string",
                ),
                Attribute(
                    name="structure",
                    path="./urf:structure",
                    datatype="string",
                    predefined_codelist="Waterway_structure",
                ),
                Attribute(
                    name="supecificBusinessFacilities",
                    path="./urf:supecificBusinessFacilities",
                    datatype="string",
                ),
                Attribute(
                    name="totalNumberOfHousing",
                    path="./urf:totalNumberOfHousing",
                    datatype="integer",
                ),
                Attribute(
                    name="utilityFacilities",
                    path="./urf:utilityFacilities",
                    datatype="string",
                ),
                Attribute(
                    name="viaLocations",
                    path="./urf:viaLocations",
                    datatype="string",
                ),
                Attribute(
                    name="width",
                    path="./urf:width",
                    datatype="double",
                ),
                # TODO: 入れ子データ
                # Attribute(
                #    name="threeDimensionalExtent",
                #    path="./urf:threeDimensionalExtent",
                #    datatype="[]urf:ThreeDimensionalExtentPropertyType",
                # ),
            ],
        ),
        AttributeGroup(
            base_element="./urf:parkAttribute/urf:ParkAttribute",
            attributes=[
                Attribute(
                    name="parkTypeNumber",
                    path="./urf:parkTypeNumber",
                    datatype="string",
                    predefined_codelist="ParkAttribute_parkTypeNumber",
                ),
                Attribute(
                    name="parkSizeNumber",
                    path="./urf:parkSizeNumber",
                    datatype="string",
                    predefined_codelist="ParkAttribute_parkSizeNumber",
                ),
                Attribute(
                    name="parkSerialNumber",
                    path="./urf:parkSerialNumber",
                    datatype="string",
                ),
            ],
        ),
        AttributeGroup(
            base_element="./urf:parkingPlaceAttribute/urf:ParkingPlaceAttribute",
            attributes=[
                Attribute(
                    name="storeysAboveGround",
                    path="./urf:storeysAboveGround",
                    datatype="integer",
                ),
                Attribute(
                    name="storeysBelowGround",
                    path="./urf:storeysBelowGround",
                    datatype="integer",
                ),
            ],
        ),
        AttributeGroup(
            base_element="./urf:sewerSystemsAttribute/urf:SewerSystemAttribute",
            attributes=[
                Attribute(
                    name="startLocation",
                    path="./urf:startLocation",
                    datatype="string",
                ),
                Attribute(
                    name="endLocation",
                    path="./urf:endLocation",
                    datatype="string",
                ),
                Attribute(
                    name="systemType",
                    path="./urf:systemType",
                    datatype="string",
                    predefined_codelist="SewerSystemAttribute_systemType",
                ),
                Attribute(
                    name="drainageArea",
                    path="./urf:drainageArea",
                    datatype="string",
                ),
            ],
        ),
        AttributeGroup(
            base_element="./urf:urbanRapidTransitRailroadAttribute/urf:UrbanRapidTransitRailroadAttribute",
            attributes=[
                Attribute(
                    name="structureType",
                    path="./urf:structureType",
                    datatype="string",
                    predefined_codelist="TrafficFacility_trafficFacilityStructureType",
                ),
                Attribute(
                    name="crossType",
                    path="./urf:crossType",
                    datatype="string",
                    predefined_codelist="TrafficFacility_trafficFacilityCrossingType",
                ),
                # TODO: 入れ子データ
                # Property(
                #     name="structuralDetails",
                #     path="./urf:structuralDetails",
                #     datatype="[]urf:StructureDetails",
                # ),
            ],
        ),
        AttributeGroup(
            base_element="./urf:urbanRoadAttribute/urf:UrbanRoadAttribute",
            attributes=[
                Attribute(
                    name="routeTypeNumber",
                    path="./urf:routeTypeNumber",
                    datatype="string",
                    predefined_codelist="UrbanRoadAttribute_routeTypeNumber",
                ),
                Attribute(
                    name="routeSizeNumber",
                    path="./urf:routeSizeNumber",
                    datatype="string",
                    predefined_codelist="UrbanRoadAttribute_routeSizeNumber",
                ),
                Attribute(
                    name="routeSerialNumber",
                    path="./urf:routeSerialNumber",
                    datatype="string",
                ),
                Attribute(
                    name="roadType",
                    path="./urf:roadType",
                    datatype="string",
                    predefined_codelist="UrbanRoadAttribute_roadType",
                ),
                Attribute(
                    name="numberOfLanes",
                    path="./urf:numberOfLanes",
                    datatype="integer",
                ),
                Attribute(
                    name="roadStructure",
                    path="./urf:roadStructure",
                    datatype="string",
                ),
                Attribute(
                    name="structureType",
                    path="./urf:structureType",
                    datatype="string",
                    predefined_codelist="TrafficFacility_trafficFacilityStructureType",
                ),
                Attribute(
                    name="crossType",
                    path="./urf:crossType",
                    datatype="string",
                    predefined_codelist="TrafficFacility_trafficFacilityCrossingType",
                ),
                Attribute(
                    name="trafficPlazas",
                    path="./urf:trafficPlazas",
                    datatype="string",
                    predefined_codelist="Common_availabilityType",
                ),
                # TODO: 入れ子データ
                # Property(
                #     name="structuralDetails",
                #     path="./urf:structuralDetails",
                #     datatype="[]urf:StructureDetails",
                # ),
            ],
        ),
        AttributeGroup(
            base_element="./urf:vehicleTerminalAttribute/urf:VehicleTerminalAttribute",
            attributes=[
                Attribute(
                    name="terminalType",
                    path="./urf:terminalType",
                    datatype="string",
                    predefined_codelist="VehicleTerminalAttribute_terminalType",
                ),
            ],
        ),
        AttributeGroup(
            base_element="./urf:waterWorksAttribute/urf:WaterWorksAttribute",
            attributes=[
                Attribute(
                    name="startLocation",
                    path="./urf:startLocation",
                    datatype="string",
                ),
                Attribute(
                    name="endLocation",
                    path="./urf:endLocation",
                    datatype="string",
                ),
            ],
        ),
    ],
    lod_detection=LODDetection(
        lod0=["./urf:lod0MultiSurface"],
        lod1=["./urf:lod1MultiSurface"],
    ),
    emissions=FeatureEmissions(
        lod0=FeatureEmission(collect_all=["./urf:lod0MultiSurface//gml:Polygon"]),
        lod1=FeatureEmission(collect_all=["./urf:lod1MultiSurface//gml:Polygon"]),
    ),
)

URF_URBAN_DEVELOPMENT_PROJECT = FeatureProcessingDefinition(
    id="urf:UrbanDevelopmentProject",
    target_elements=[
        "urf:DisasterPreventionBlockImprovementProject",
        "urf:IndustrialParkDevelopmentProject",
        "urf:LandReadjustmentProject",
        "urf:NewHousingAndUrbanDevelopmentProject",
        "urf:NewUrbanInfrastructureProject",
        "urf:ResidentialBlockConstructionProject",
        "urf:UrbanDevelopmentProject",
        "urf:UrbanRedevelopmentProject",
        "urf:UrbanRenewalProject",
    ],
    attribute_groups=[
        *_base_attributes,
        AttributeGroup(
            base_element=None,
            attributes=[
                Attribute(
                    name="function",
                    path="./urf:function",
                    datatype="[]string",
                    predefined_codelist="UrbanDevelopmentProject_function",
                ),
                Attribute(
                    name="usage",
                    path="./urf:usage",
                    datatype="[]string",
                ),
                Attribute(
                    name="buildingLotDevelopment",
                    path="./urf:buildingLotDevelopment",
                    datatype="string",
                ),
                Attribute(
                    name="buildingUsage",
                    path="./urf:buildingUsage",
                    datatype="string",
                ),
                Attribute(
                    name="developmentPlan",
                    path="./urf:developmentPlan",
                    datatype="string",
                ),
                Attribute(
                    name="disasterPreventionPublicFacilityAllocation",
                    path="./urf:disasterPreventionPublicFacilityAllocation",
                    datatype="string",
                ),
                Attribute(
                    name="districtsAllocation",
                    path="./urf:districtsAllocation",
                    datatype="string",
                ),
                Attribute(
                    name="floorAreaRate",
                    path="./urf:floorAreaRate",
                    datatype="double",
                ),
                Attribute(
                    name="housing",
                    path="./urf:housing",
                    datatype="string",
                ),
                Attribute(
                    name="housingTarget",
                    path="./urf:housingTarget",
                    datatype="string",
                ),
                Attribute(
                    name="landForCentralPublicFacilities",
                    path="./urf:landForCentralPublicFacilities",
                    datatype="string",
                ),
                Attribute(
                    name="landUsePlan",
                    path="./urf:landUsePlan",
                    datatype="string",
                ),
                Attribute(
                    name="numberOfHousing",
                    path="./urf:numberOfHousing",
                    datatype="integer",
                ),
                Attribute(
                    name="otherPublicFacilityAllocation",
                    path="./urf:otherPublicFacilityAllocation",
                    datatype="string",
                ),
                Attribute(
                    name="publicFacilityAllocation",
                    path="./urf:publicFacilityAllocation",
                    datatype="string",
                ),
                Attribute(
                    name="residentialLandUsePlan",
                    path="./urf:residentialLandUsePlan",
                    datatype="string",
                ),
                Attribute(
                    name="scheduledExecutor",
                    path="./urf:scheduledExecutor",
                    datatype="string",
                ),
                Attribute(
                    name="setbackSize",
                    path="./urf:setbackSize",
                    datatype="string",
                ),
                Attribute(
                    name="siteArea",
                    path="./urf:siteArea",
                    datatype="double",
                ),
                Attribute(
                    name="storeysAboveGround",
                    path="./urf:storeysAboveGround",
                    datatype="integer",
                ),
                Attribute(
                    name="storeysBelowGround",
                    path="./urf:storeysBelowGround",
                    datatype="integer",
                ),
                Attribute(
                    name="totalFloorArea",
                    path="./urf:totalFloorArea",
                    datatype="double",
                ),
            ],
        ),
    ],
    lod_detection=LODDetection(
        lod0=["./urf:lod0MultiSurface"],
        lod1=["./urf:lod1MultiSurface"],
    ),
    emissions=FeatureEmissions(
        lod0=FeatureEmission(collect_all=["./urf:lod0MultiSurface//gml:Polygon"]),
        lod1=FeatureEmission(collect_all=["./urf:lod1MultiSurface//gml:Polygon"]),
    ),
)

URF_SCHEDULED_AREA_FOR_URBAN_DEVELOPMENT = FeatureProcessingDefinition(
    id="urf:ScheduledAreaForUrbanDevelopmentProject",
    target_elements=[
        "urf:ScheduledAreaForCollectiveGovernmentAndPublicOfficeFacilities",
        "urf:ScheduledAreaForCollectiveHousingFacilities",
        "urf:ScheduledAreaForDistributionBusinessPark",
        "urf:ScheduledAreaForIndustrialParkDevelopmentProjects",
        "urf:ScheduledAreaForNewHousingAndUrbanDevelopmentProjects",
        "urf:ScheduledAreaForNewUrbanInfrastructureProjects",
        "urf:ScheduledAreaForUrbanDevelopmentProject",
    ],
    attribute_groups=[
        *_base_attributes,
        AttributeGroup(
            base_element=None,
            attributes=[
                Attribute(
                    name="function",
                    path="./urf:function",
                    datatype="[]string",
                    predefined_codelist="ScheduledAreaForUrbanDevelopment_function",
                ),
                Attribute(
                    name="scheduledExecutor",
                    path="./urf:scheduledExecutor",
                    datatype="string",
                ),
            ],
        ),
    ],
    lod_detection=LODDetection(
        lod0=["./urf:lod0MultiSurface"],
        lod1=["./urf:lod1MultiSurface"],
    ),
    emissions=FeatureEmissions(
        lod0=FeatureEmission(collect_all=["./urf:lod0MultiSurface//gml:Polygon"]),
        lod1=FeatureEmission(collect_all=["./urf:lod1MultiSurface//gml:Polygon"]),
    ),
)

URF_DISTRICT_PLAN = FeatureProcessingDefinition(
    id="urf:DistrictPlan",
    target_elements=[
        "urf:DisasterPreventionBlockImprovementZonePlan",
        "urf:DistrictPlan",
        "urf:HistoricSceneryMaintenanceAndImprovementDistrictPlan",
        "urf:RoadsideDistrictPlan",
        "urf:RuralDistrictPlan",
    ],
    attribute_groups=[
        *_base_attributes,
        AttributeGroup(
            base_element=None,
            attributes=[
                Attribute(
                    name="function",
                    path="./urf:function",
                    datatype="[]string",
                    predefined_codelist="DistrictPlan_function",
                ),
                Attribute(
                    name="facilitiesAllocation",
                    path="./urf:facilitiesAllocation",
                    datatype="string",
                ),
                Attribute(
                    name="facilityAllocation",
                    path="./urf:facilityAllocation",
                    datatype="string",
                ),
                Attribute(
                    name="landUsePolicy",
                    path="./urf:landUsePolicy",
                    datatype="string",
                ),
                Attribute(
                    name="objectives",
                    path="./urf:objectives",
                    datatype="string",
                ),
                Attribute(
                    name="policy",
                    path="./urf:policy",
                    datatype="string",
                ),
                Attribute(
                    name="specifiedZonalDisasterPreventionFacilitiesAllocation",
                    path="./urf:specifiedZonalDisasterPreventionFacilitiesAllocation",
                    datatype="string",
                ),
                Attribute(
                    name="zonalDisasterPreventionFacilitiesAllocation",
                    path="./urf:zonalDisasterPreventionFacilitiesAllocation",
                    datatype="string",
                ),
            ],
        ),
    ],
    lod_detection=LODDetection(
        lod0=["./urf:lod0MultiSurface"],
        lod1=["./urf:lod1MultiSurface"],
    ),
    emissions=FeatureEmissions(
        lod0=FeatureEmission(collect_all=["./urf:lod0MultiSurface//gml:Polygon"]),
        lod1=FeatureEmission(collect_all=["./urf:lod1MultiSurface//gml:Polygon"]),
        semantic_parts=[
            "./urf:districtDevelopmentPlan/urf:*",
            "./urf:promotionDistrict/urf:*",
            "./urf:zonalDisasterPreventionFacilities/urf:ZonalDisasterPreventionFacility",
        ],
    ),
)

URF_DISTRICT_DEVELOPMENT_PLAN = FeatureProcessingDefinition(
    id="urf:DistrictDevelopmentPlan",
    target_elements=[
        "urf:DistrictDevelopmentPlan",
        "urf:DistrictImprovementPlanForDisasterPreventionBlockImprovementZonePlan",
        "urf:DistrictImprovementPlanForHistoricSceneryMaintenanceAndImprovementDistrict",
        "urf:RoadsideDistrictImprovementPlan",
        "urf:RuralDistrictImprovementPlan",
        "urf:SpecifiedBuildingZoneImprovementPlan",
    ],
    attribute_groups=[
        *_base_attributes,
        AttributeGroup(
            base_element=None,
            attributes=[
                Attribute(
                    name="function",
                    path="./urf:function",
                    datatype="[]string",
                    predefined_codelist="DistrictDevelopmentPlan_function",
                ),
                Attribute(
                    name="activityRestrictionInFarmland",
                    path="./urf:activityRestrictionInFarmland",
                    datatype="string",
                ),
                Attribute(
                    name="buildingRestrictions",
                    path="./urf:buildingRestrictions",
                    datatype="string",
                ),
                Attribute(
                    name="districtFacilitiesAllocation",
                    path="./urf:districtFacilitiesAllocation",
                    datatype="string",
                ),
                Attribute(
                    name="landuseRestrictions",
                    path="./urf:landuseRestrictions",
                    datatype="string",
                ),
                Attribute(
                    name="roadsideDistrictFacilitiesAllocation",
                    path="./urf:roadsideDistrictFacilitiesAllocation",
                    datatype="string",
                ),
                Attribute(
                    name="ruralDistrictFacilitiesAllocation",
                    path="./urf:ruralDistrictFacilitiesAllocation",
                    datatype="string",
                ),
                Attribute(
                    name="urbanGreenSpaceConservation",
                    path="./urf:urbanGreenSpaceConservation",
                    datatype="string",
                ),
            ],
        ),
    ],
    lod_detection=LODDetection(
        lod0=["./urf:lod0MultiSurface"],
        lod1=["./urf:lod1MultiSurface"],
    ),
    emissions=FeatureEmissions(
        lod0=FeatureEmission(collect_all=["./urf:lod0MultiSurface//gml:Polygon"]),
        lod1=FeatureEmission(collect_all=["./urf:lod1MultiSurface//gml:Polygon"]),
        semantic_parts=[
            "./urf:district/urf:District",
            "./urf:districtFacility/urf:*",
        ],
    ),
)

URF_DISTRICT_FACILITY = FeatureProcessingDefinition(
    id="urf:DistrictFacility",
    target_elements=[
        "urf:DistrictFacility",
        "urf:RoadsideDistrictFacility",
        "urf:RuralDistrictFacility",
        "urf:ZonalDisasterPreventionFacility",
    ],
    attribute_groups=[
        *_base_attributes,
        AttributeGroup(
            base_element=None,
            attributes=[
                Attribute(
                    name="function",
                    path="./urf:function",
                    datatype="[]string",
                    predefined_codelist="Common_districtFacilityType",
                ),
                Attribute(
                    name="usage",
                    path="./urf:usage",
                    datatype="[]string",
                    predefined_codelist="UrbanFacility_function",
                ),
                Attribute(
                    name="facilityType",
                    path="./urf:facilityType",
                    datatype="string",
                    predefined_codelist="ZonalDisasterPreventionFacility_facilityType",
                ),
            ],
        ),
    ],
    lod_detection=LODDetection(
        lod0=["./urf:lod0MultiSurface"],
        lod1=["./urf:lod1MultiSurface"],
    ),
    emissions=FeatureEmissions(
        lod0=FeatureEmission(collect_all=["./urf:lod0MultiSurface//gml:Polygon"]),
        lod1=FeatureEmission(collect_all=["./urf:lod1MultiSurface//gml:Polygon"]),
    ),
)

URF_PROMOTION_DISTRICT = FeatureProcessingDefinition(
    id="urf:PromotionDistrict",
    target_elements=["urf:PromotionDistrict"],
    attribute_groups=[
        *_base_attributes,
        AttributeGroup(
            base_element=None,
            attributes=[
                Attribute(
                    name="function",
                    path="./urf:function",
                    datatype="[]string",
                    predefined_codelist="PromotionArea_function",
                ),
            ],
        ),
    ],
    lod_detection=LODDetection(
        lod0=["./urf:lod0MultiSurface"],
        lod1=["./urf:lod1MultiSurface"],
    ),
    emissions=FeatureEmissions(
        lod0=FeatureEmission(collect_all=["./urf:lod0MultiSurface//gml:Polygon"]),
        lod1=FeatureEmission(collect_all=["./urf:lod1MultiSurface//gml:Polygon"]),
    ),
)

URF_DISTRICT = FeatureProcessingDefinition(
    id="urf:District",
    target_elements=["urf:District"],
    attribute_groups=[
        *_base_attributes,
        AttributeGroup(
            base_element=None,
            attributes=[
                Attribute(
                    name="function",
                    path="./urf:function",
                    datatype="[]string",
                    predefined_codelist="District_function",
                ),
                Attribute(
                    name="buildingDesignRestriction",
                    path="./urf:buildingDesignRestriction",
                    datatype="string",
                ),
                Attribute(
                    name="buildingRestrictions",
                    path="./urf:buildingRestrictions",
                    datatype="string",
                ),
                Attribute(
                    name="fenceGuideline",
                    path="./urf:fenceGuideline",
                    datatype="string",
                ),
                Attribute(
                    name="maximumBuildingCoverageRate",
                    path="./urf:maximumBuildingCoverageRate",
                    datatype="double",
                ),
                Attribute(
                    name="maximumBuildingHeight",
                    path="./urf:maximumBuildingHeight",
                    datatype="double",
                ),
                Attribute(
                    name="maximumFloorAreaRate",
                    path="./urf:maximumFloorAreaRate",
                    datatype="double",
                ),
                Attribute(
                    name="minimumBuildingArea",
                    path="./urf:minimumBuildingArea",
                    datatype="double",
                ),
                Attribute(
                    name="minimumBuildingCoverageRate",
                    path="./urf:minimumBuildingCoverageRate",
                    datatype="double",
                ),
                Attribute(
                    name="minimumBuildingHeight",
                    path="./urf:minimumBuildingHeight",
                    datatype="double",
                ),
                Attribute(
                    name="minimumFloorAreaRate",
                    path="./urf:minimumFloorAreaRate",
                    datatype="double",
                ),
                Attribute(
                    name="minimumFloorHeight",
                    path="./urf:minimumFloorHeight",
                    datatype="double",
                ),
                Attribute(
                    name="minimumFrontageRate",
                    path="./urf:minimumFrontageRate",
                    datatype="double",
                ),
                Attribute(
                    name="minimumGreeningRate",
                    path="./urf:minimumGreeningRate",
                    datatype="double",
                ),
                Attribute(
                    name="minimumGroundHeight",
                    path="./urf:minimumGroundHeight",
                    datatype="double",
                ),
                Attribute(
                    name="minimumSiteArea",
                    path="./urf:minimumSiteArea",
                    datatype="double",
                ),
                Attribute(
                    name="restrictionsForFireProtection",
                    path="./urf:restrictionsForFireProtection",
                    datatype="string",
                ),
                Attribute(
                    name="restrictionsForNoiseProtection",
                    path="./urf:restrictionsForNoiseProtection",
                    datatype="string",
                ),
                Attribute(
                    name="setbackSize",
                    path="./urf:setbackSize",
                    datatype="string",
                ),
                Attribute(
                    name="structurePlacementRestrictions",
                    path="./urf:structurePlacementRestrictions",
                    datatype="string",
                ),
                Attribute(
                    name="useRestrictions",
                    path="./urf:useRestrictions",
                    datatype="string",
                ),
            ],
        ),
    ],
    lod_detection=LODDetection(
        lod0=["./urf:lod0MultiSurface"],
        lod1=["./urf:lod1MultiSurface"],
    ),
    emissions=FeatureEmissions(
        lod0=FeatureEmission(collect_all=["./urf:lod0MultiSurface//gml:Polygon"]),
        lod1=FeatureEmission(collect_all=["./urf:lod1MultiSurface//gml:Polygon"]),
    ),
)
