name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  Lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv
          
      - name: Set up cache
        uses: actions/cache@v4
        id: cache
        with:
          path: .venv
          key: venv-lint-${{ hashFiles('**/uv.lock') }}

      - name: Ensure cache is healthy
        if: steps.cache.outputs.cache-hit == 'true'
        run: uv run python --version >/dev/null 2>&1 || rm -rf .venv

      - name: Install dependencies
        run: uv sync

      - name: ruff (format)
        run: uv run ruff format --check .

      - name: ruff (lint)
        run: uv run ruff check --output-format github .
